### ISSUE TITLE
pandoc-citeproc issue: Incorrect encoding of BibTeX file

### ISSUE THREAD

**Issue by JimGrange** [crsh/papaja#123] opened 2017-06-30 07:56 UTC
This might not be a papaja issue, but I thought I'd ask anyway...

The template loads and compiles just fine, producing PDF. However, I tried adding a plot using the code below, and now the markdown will not compile:

```
{r, include = TRUE}
set.seed(42)
subject <- rep(c(1:5), each = 4)
task <- gl(2, 2, length = 20, labels = c("Repetition", "Switch"))
cue <- gl(2, 1, length = 20, labels = c("Shape", "Arrows"))
rt <- rnorm(20, 500, 70)
data <- data.frame(subject = subject, task = task, cue = cue, rt = rt)

apa_beeplot(
  data,
  id = "subject",
  dv = "rt",
  factors = c("task", "cue"),
  dispersion = conf_int,
  ylim = c(300, 1000),
  las = 1
)
```

I get the error message:

```
pandoc-citeproc: Cannot decode byte '\xfc': Data.Text.Internal.Encoding.Fusion.streamUtf8: Invalid UTF-8 stream
pandoc.exe: Error running filter pandoc-citeproc
Filter returned error status 1
Error: pandoc document conversion failed with error 83
```

The strange thing is is that now when I delete the code for the plot, it still won't compile (even though the code is exactly the same as when it did compile). It also won't compile if I load a new blank template, so adding the plot has obviously made something go awry, but I am not sure what. 

My session info:

```
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.4.0    backports_1.1.0   magrittr_1.5      rprojroot_1.2     htmltools_0.3.6   tools_3.4.0      
 [7] yaml_2.1.14       Rcpp_0.12.11      stringi_1.1.5     rmarkdown_1.6     papaja_0.1.0.9492 knitr_1.16       
[13] stringr_1.2.0     digest_0.6.12     evaluate_0.10.1 
```

**Comment by crsh** [comment] 2017-06-30 12:36
Hi Jim,

thanks for bringing this to my attention. I've received a similar report just recently. In this case I was unfortunately unable to reproduce the problem, which makes it difficult to diagnose and fix. From what I have gathered so far I suspect it has to do with the encoding of the R Markdown file. To verify that this is specific to `papaja`, could you try adding the same code to the default `rmarkdown` PDF document template? (I am AFK right now, so I can't test it myself. )

Sent from my phone

**Comment by JimGrange** [comment] 2017-06-30 12:40
Thanks for swift reply. I've added my plot code to the default rmarkdown template in RStudio and it compiles fine to both PDF and html.

**Comment by crsh** [comment] 2017-07-03 16:37
I'm having trouble reproducing this issue. Could you try removing the bibliography file from the YAML header (assuming you have added one) to test whether the encoding error is within the R Markdown or the BibTeX document?

**Comment by JimGrange** [comment] 2017-07-03 17:02
Oh, that's interesting. So, I am just using your template that launches in R-Studio. If I remove the bib from YAML the error doesn't occur.

**Comment by crsh** [comment] 2017-07-03 17:40
Okay, so then I suspect that the error is due to the encoding of the BibTeX file. If I understand you correctly, that file is generated by `r_refs(file = "r-references.bib")`?

I think I know what's causing the issue. Since I can reproduce the error, please bare with me. Could you try installing the current development version of `papaja` to verify that the issue persists (`devtools::install_github("crsh/papaja@devel")`)? Once you have done this I will push a commit with the suspected fix and ask you to try again. This is a little complicated but I don't currently see a different way to fix this remotely.

**Comment by crsh** [comment] 2017-07-03 17:43
Maybe we could first try something else. Could you upload the faulty BibTeX file here? I would then first try to reproduce the issue on my machine. That would make things easier.

**Comment by JimGrange** [comment] 2017-07-04 15:39
Git won't allow me to upload a .bib file, so I've put it in a zipped folder. This is the bib file that is automatically generated by the default template of papaja.

[faulty bib.zip](https://github.com/crsh/papaja/files/1122520/faulty.bib.zip)

**Comment by JimGrange** [comment] 2017-07-04 15:40
The bug persists with the developmental version of papaja.

**Comment by crsh** [comment] 2017-07-04 16:54
Great, thanks.

It is indeed the encoding of the BibTeX file. As you can see from the abbreviated output, if you read the file manually the Umlaut in the second reference is the Byte `\xfc` that cannot be decoded by `pandoc-citeproc` because it expects a UTF-8 encoded file:

``` r
readLines("faulty bib/r-references.bib", encoding = "UTF-8")
#>  [1] "@Manual{R-base,"
# [...]         
#>  [9] "@Manual{R-bindrcpp,"                                                 
#> [10] "  title = {bindrcpp: An 'Rcpp' Interface to Active Bindings},"       
#> [11] "  author = {Kirill M\xfcller},"                                      
#> [12] "  year = {2017},"                                                    
#> [13] "  note = {R package version 0.2},"                                   
#> [14] "  url = {https://CRAN.R-project.org/package=bindrcpp},"              
#> [15] "}"                                                                   
# [...]                            
#> [22] "}"
```
This is a bug in `r_refs()`. I just pushed a fix to the `devel` branch. Try reinstalling papaja from there, delete the faulty BibTeX file `r-references.bib`, and knit the document again.

Thanks again for bringing this to my attention and let me know if it works. By the way, should ever have to upload a text file again, you can simply change the file extension to `.txt` before you upload it to GitHub. No need to wrap it in a `.zip` file.

**Comment by JimGrange** [comment] 2017-07-04 18:07
It now works like a charm - thanks for looking into it! Now I have no excuse to not start writing...

**Comment by crsh** [comment] 2017-07-04 18:45
Excellent! Thanks again for the bug report and testing.

**Closed** 2017-11-29 01:40 UTC
Labels: bug

**Comment by JobNmadu** [comment] 2020-09-23 00:38
Yap the problem is not a bug but the list of authors is too lengthy. Try to cite tidyverse, then the error resonates!
