### ISSUE TITLE
Figures after first display low on pages

### ISSUE THREAD

**Issue by lolNickFox** [crsh/papaja#237] opened 2018-08-02 07:24 UTC
Hello!
I'm trying to produce a pdf with multiple figures.  On the figure pages at the end of the document, figures 2, 3, and any other subsequent figures have extra white space above them.  This doesn't seem to ever be a problem with the first figure.  Here is a minimum example that has the issue for me when I knit to apa6 pdf

~~~
---
title             : "The title"
shorttitle        : "Title"

author: 
  - name          : "First Author"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Postal address"
    email         : "my@email.com"
  - name          : "Ernst-August Doelle"
    affiliation   : "1,2"

affiliation:
  - id            : "1"
    institution   : "Wilhelm-Wundt-University"
  - id            : "2"
    institution   : "Konstanz Business School"

author_note: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.

abstract: |
  Enter abstract here. Each new line herein must be indented, like this line.
  
keywords          : "keywords"
wordcount         : "X"

bibliography      : ["r-references.bib"]

figsintext        : no
figurelist        : no
tablelist         : no
footnotelist      : no
lineno            : no
mask              : no

class             : "man"
output            : papaja::apa6_pdf
---

```{r load_packages, include = FALSE}
library("papaja")
```

```{r analysis_preferences}
# Seed for random number generation
set.seed(42)
```



# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.

```{r echo = FALSE, fig.height = 3, fig.width = 7, fig.cap = "\\label{fig:fig1}This is the first figure."}
# Define the cars vector with 5 values
cars <- c(1, 3, 6, 4, 9)

# Graph the cars vector with all defaults
plot(cars)


```

```{r echo = FALSE, fig.height = 3, fig.width = 7, fig.cap = "\\label{fig:fig1}This is the second figure."}
# Define the cars vector with 5 values
cars <- c(1, 3, 6, 4, 9)

# Graph the cars vector with all defaults
plot(cars)


```



# Results

# Discussion


\newpage

# References
```{r create_r-references}
r_refs(file = "r-references.bib")
```

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>
\endgroup

~~~
[figure_test.pdf](https://github.com/crsh/papaja/files/2252509/figure_test.pdf)

**Comment by crsh** [comment] 2018-08-02 12:08
Hi Nick, thanks for reach out. When I knit this document it comes out as expected. Could you post the output of `devtools::session_info()`, `rmarkdown::pandoc_version()`, and provide the version of your LaTeX distribution?

**Comment by crsh** [comment] 2018-08-02 12:09
Oh, and could you try installing the development version of `papaja` (`devtools::install_github("crsh/papaja@devel")`) to see if that helps?

**Comment by lolNickFox** [comment] 2018-08-02 23:10
thanks so much for the quick reply!  Installing the development version of papaja didn't fix it.  rmarkdown::pandoc_version() threw me an error (object rmarkdown not found) - I installed the rmarkdown package and tried again, but still got the error.  Running pandoc_version() gives me: [1] ‘1.19.2.1’, and below is my devtools::session_info()

 package    * version    date       source                      
 assertthat   0.2.0      2017-04-11 CRAN (R 3.4.0)              
 backports    1.1.2      2017-12-13 cran (@1.1.2)               
 base       * 3.4.1      2017-07-07 local                       
 bindr        0.1.1      2018-03-13 CRAN (R 3.4.4)              
 bindrcpp     0.2.2      2018-03-29 CRAN (R 3.4.4)              
 colorspace   1.3-2      2016-12-14 CRAN (R 3.4.0)              
 compiler     3.4.1      2017-07-07 local                       
 crayon       1.3.4      2017-09-16 CRAN (R 3.4.1)              
 datasets   * 3.4.1      2017-07-07 local                       
 devtools     1.13.6     2018-06-27 CRAN (R 3.4.4)              
 digest       0.6.15     2018-01-28 CRAN (R 3.4.3)              
 dplyr        0.7.6      2018-06-29 CRAN (R 3.4.4)              
 evaluate     0.11       2018-07-17 CRAN (R 3.4.4)              
 ggplot2      3.0.0      2018-07-03 CRAN (R 3.4.4)              
 glue         1.3.0      2018-07-17 CRAN (R 3.4.4)              
 graphics   * 3.4.1      2017-07-07 local                       
 grDevices  * 3.4.1      2017-07-07 local                       
 grid         3.4.1      2017-07-07 local                       
 gtable       0.2.0      2016-02-26 CRAN (R 3.4.0)              
 htmltools    0.3.6      2017-04-28 cran (@0.3.6)               
 knitr        1.20       2018-02-20 cran (@1.20)                
 lazyeval     0.2.1      2017-10-29 CRAN (R 3.4.2)              
 magrittr     1.5        2014-11-22 CRAN (R 3.4.0)              
 memoise      1.1.0      2017-04-21 CRAN (R 3.4.0)              
 methods    * 3.4.1      2017-07-07 local                       
 munsell      0.5.0      2018-06-12 CRAN (R 3.4.4)              
 papaja       0.1.0.9793 2018-08-02 Github (crsh/papaja@fb07d2f)
 pillar       1.3.0      2018-07-14 CRAN (R 3.4.4)              
 pkgconfig    2.0.1      2017-03-21 CRAN (R 3.4.0)              
 plyr         1.8.4      2016-06-08 CRAN (R 3.4.0)              
 purrr        0.2.5      2018-05-29 CRAN (R 3.4.4)              
 R6           2.2.2      2017-06-17 CRAN (R 3.4.0)              
 Rcpp         0.12.18    2018-07-23 CRAN (R 3.4.4)              
 rlang        0.2.1      2018-05-30 CRAN (R 3.4.4)              
 rmarkdown  * 1.10       2018-06-11 CRAN (R 3.4.4)              
 rprojroot    1.3-2      2018-01-03 cran (@1.3-2)               
 rstudioapi   0.7        2017-09-07 CRAN (R 3.4.1)              
 scales       0.5.0      2017-08-24 CRAN (R 3.4.1)              
 stats      * 3.4.1      2017-07-07 local                       
 stringi      1.2.4      2018-07-20 CRAN (R 3.4.4)              
 stringr      1.3.1      2018-05-10 cran (@1.3.1)               
 tibble       1.4.2      2018-01-22 CRAN (R 3.4.3)              
 tidyselect   0.2.4      2018-02-26 CRAN (R 3.4.3)              
 tools        3.4.1      2017-07-07 local                       
 utils      * 3.4.1      2017-07-07 local                       
 withr        2.1.2      2018-03-15 CRAN (R 3.4.4)              
 yaml         2.2.0      2018-07-25 cran (@2.2.0) 

Thanks so much for the help!

**Comment by crsh** [comment] 2018-08-03 10:04
Hmm, ... Could you also provide your locale, operating system and RStudio version (those are all usually included in the output of `session_info()` and upload the `.tex` file that produces this behavior?

**Comment by lolNickFox** [comment] 2018-08-03 17:09
Totally.  I'm in South Orange, New Jersey USA.  RStudio Version 1.1.350. Attached is the .tex (I had to zip it to attach to this comment).  Thanks!
[figure_test.tex.zip](https://github.com/crsh/papaja/files/2258150/figure_test.tex.zip)

**Comment by crsh** [comment] 2018-08-06 10:37
So, I can reproduce this on Windows with MikTeX, but I have no idea, what is causing this. The issue is that instead of putting figures on separate page, the pages are filled with multiple figures. The LaTeX `endfloat` package allows adjusting the endfloat separator (e.g., `\renewcommand{\efloatseparator}{\clearpage}` should be the default), but it doesn't seem to have any effect for me. I've tried getting this to work in the bare example document in the `apa6` manual, but to no avail. I think this would be well suited for a question on [StackExchange}(https://tex.stackexchange.com) as I suspect this is a LaTeX issue. If you find a solution, I'd be very interested in it.

I'll close this issue for now, but feel free to reopen it to discuss this further if you need.

**Closed** 2018-08-07 13:45 UTC
Labels: unrelated
