### ISSUE TITLE
Issue with col_spanners option in apa_table

### ISSUE THREAD

**Issue by PenelopeLQ** [crsh/papaja#167] opened 2017-12-20 21:07 UTC
Hi,
I'm using apa_table to produce a a table with multi-row header. I thought col_spanners could do the trick. Here is an example I found on R Documentation

~~~r
my_table <- t(apply(cars, 2, function(x) # Create data
  round(c(Mean = mean(x), SD = sd(x), Min = min(x), Max = max(x)), 2)
))

apa_table(
  cbind(my_table, my_table)
  , align = c("l", rep("r", 10))
  , caption = "A summary table of the cars dataset."
  , note = "This table was created using apa\\_table()"
  , added_stub_head = "Variables"
  , col_spanners = list(`Cars 1` = c(2, 5), `Cars 2` = c(6, 9))
)
~~~

When I run it in R, even though it doesn't give me a table, I can see the information of row header is there:

~~~
\toprule
 & \multicolumn{4}{c}{Cars 1} & \multicolumn{4}{c}{Cars 2} \\
\cmidrule(r){2-5} \cmidrule(r){6-9}
~~~

But when i knit it to word or pdf, the headers just don't show up. In word, there is no column spanners; and in pdf, there's nothing at all. (To be fair, I'm experiencing problem with knitting to pdf because RStudio still can't find pdflatex. I have to knit it to .tex first and then build it again in TexMaker. So, that might be the problem. But when knitting to word, there's no other problems but this).

Any help would be greatly appreciated!

P

**Comment by crsh** [comment] 2017-12-21 10:28
Hi Penelope,

when I include the following code in a new `papaja` document it renders to PDF as expected.

~~~markdown
```{r results = "asis"}
my_table <- t(apply(cars, 2, function(x) # Create data
  round(c(Mean = mean(x), SD = sd(x), Min = min(x), Max = max(x)), 2)
))

apa_table(
  cbind(my_table, my_table)
  , align = c("l", rep("r", 10))
  , caption = "A summary table of the cars dataset."
  , added_stub_head = "Variables"
  , col_spanners = list(`Cars 1` = c(2, 5), `Cars 2` = c(6, 9))
)
```
~~~

Does this not work on your computer?

If this is not the case for you, please ensure that you are working with the latest version of `papaja` and provide a minimal reproducible example of an R Markdown file that produces the unexpected behavior your describe.

As documented, due to limitations of `pandoc`, `col_spanners` is not supported in Word documents.

**Comment by crsh** [comment] 2018-01-29 17:00
I will close this issue; if you are still experiencing issues feel free reopen.

**Closed by crsh** 2018-01-29 17:00 UTC
