### ISSUE TITLE
pandoc eliminates parts of the table-related header-includes

### ISSUE THREAD

**Issue by mischavk** [crsh/papaja#227] opened 2018-07-03 13:09 UTC
Hi,
thanks for the great package, I really enjoy it!
However, I've encountered a small issue with the apa_table function. I want to show a varying number of digits for different columns. This can be done using the "digits" parameter in kable and works just fine when I use kable directly. But when I add the "digits" parameter to the apa_table command, the vector specified is applied to rows instead of columns. I don't understand why and what can be done to prevent this? 

See code example:

```{r load_packages, results='asis'}
library("papaja")
library("knitr")
df <- data.frame(c(2.2,3.5,4.4,5.5),c(2.2,3.5,4.4,5.5))
apa_table(
  df
  , caption = "bla"
  , note = "This table was created with apa_table()."
  , escape = TRUE
  , digits = c(2,0))

# this works just fine:
kable(df, format = "latex", digits = c(2,0))
```

Best, Mischa

**Comment by crsh** [comment] 2018-07-03 14:15
Hi Mischa, thanks for reaching out. This problem has been fixed in the development version (`devtools::install_github("crsh/papaja@devel")`). Alternatively, you can pass the `digits` argument as part of `format.args`. Note, that the behavior in `apa_table()` is slightly different than in `kable()` in that it fills in trailing 0 until the desired number digits is reached.  Let me know if that works for you.

**Comment by crsh** [comment] 2018-07-04 07:52
Could you provide the error message you get when the document compilation fails? Also, I'm afraid I forgot to add `@devel` to the installation call when I posted my answer and edited it in after a minute. Did you install via `devtools::install_github("crsh/papaja@devel")`?

Here is the output I get:

~~~r
> library("papaja")
> library("knitr")
> df <- data.frame(c(2.2,3.5,4.4,5.5),c(2.2,3.5,4.4,5.5))
> apa_table(
+   df
+   , caption = "bla"
+   , note = "This table was created with apa_table()."
+   , escape = TRUE
+   , digits = c(2,0))
~~~
~~~
\begin{table}[tbp]
\begin{center}
\begin{threeparttable}
\caption{bla}
\begin{tabular}{ll}
\toprule
c.2.2..3.5..4.4..5.5. & \multicolumn{1}{c}{c.2.2..3.5..4.4..5.5..1}\\
\midrule
2.20 & 2\\
3.50 & 4\\
4.40 & 4\\
5.50 & 6\\
\bottomrule
\addlinespace
\end{tabular}
\begin{tablenotes}[para]
\textit{Note.} This table was created with apa\_table().
\end{tablenotes}
\end{threeparttable}
\end{center}
\end{table}
~~~
~~~r
> # this works just fine:
> kable(df, format = "latex", digits = c(2,0))
~~~
~~~
\begin{tabular}{r|r}
\hline
c.2.2..3.5..4.4..5.5. & c.2.2..3.5..4.4..5.5..1\\
\hline
2.2 & 2\\
\hline
3.5 & 4\\
\hline
4.4 & 4\\
\hline
5.5 & 6\\
\hline
\end{tabular}
~~~

**Comment by mischavk** [comment] 2018-07-04 10:05
Here's the output:

```
Error: Failed to compile sfimarkdown.tex. See sfimarkdown.log for more info.
Execution halted
```

The log-file ends with
```
                   [tbp] 
Here is how much of TeX's memory you used:
 15368 strings out of 494953
 224663 string characters out of 6180977
 329495 words of memory out of 5000000
 18384 multiletter control sequences out of 15000+600000
 48237 words of font info for 56 fonts, out of 8000000 for 9000
 14 hyphenation exceptions out of 8191
 43i,10n,47p,798b,406s stack positions out of 5000i,500n,10000p,200000b,80000s

!  ==> Fatal error occurred, no output PDF file produced!
```

**Comment by crsh** [comment] 2018-07-04 10:35
Hmm, I cannot reproduce this error. Do you get this error message when you knit a newly created papaja document to which you have made no changes but added the code in your original post?

**Comment by mischavk** [comment] 2018-07-04 10:47
Yup, I created a new papaja document and only added:

```

```{r test, results='asis'}
library("papaja")
df <- data.frame(c(2.2,3.5,4.4,5.5),c(2.2,3.5,4.4,5.5))
apa_table(
  df
  , caption = "bla"
  , note = "This table was created with apa_table()."
  , escape = TRUE
  , digits = c(1,0)
)
```
I also get his error:
```
! Missing \endcsname inserted.
<to be read again> 
                   \def 
l.116 \begin{table}
```
If don't insert this chunk of code, the knitting works. It also works when I don't use the  development version (but then the original error occurs).

**Comment by mischavk** [comment] 2018-07-04 11:37
Here are the rmd and log files:
[test.zip](https://github.com/crsh/papaja/files/2163061/test.zip)

Here's the output:
```
>  devtools::session_info()
Session info ------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 system   x86_64, linux-gnu           
 ui       RStudio (1.2.755)           
 language en_US                       
 collate  en_US.UTF-8                 
 tz       Europe/Berlin               
 date     2018-07-04                  

Packages ----------------------------------------------------------------------------------------------------------------------------------
 package   * version    date       source                      
 backports   1.1.2      2017-12-13 CRAN (R 3.5.1)              
 base      * 3.5.1      2018-07-03 local                       
 compiler    3.5.1      2018-07-03 local                       
 datasets  * 3.5.1      2018-07-03 local                       
 devtools    1.13.6     2018-06-27 CRAN (R 3.5.1)              
 digest      0.6.15     2018-01-28 CRAN (R 3.5.1)              
 evaluate    0.10.1     2017-06-24 CRAN (R 3.5.1)              
 graphics  * 3.5.1      2018-07-03 local                       
 grDevices * 3.5.1      2018-07-03 local                       
 htmltools   0.3.6      2017-04-28 CRAN (R 3.5.1)              
 knitr     * 1.20       2018-02-20 CRAN (R 3.5.1)              
 magrittr    1.5        2014-11-22 CRAN (R 3.5.1)              
 memoise     1.1.0      2017-04-21 CRAN (R 3.5.1)              
 methods   * 3.5.1      2018-07-03 local                       
 papaja    * 0.1.0.9735 2018-07-04 Github (crsh/papaja@3553f2a)
 Rcpp        0.12.17    2018-05-18 CRAN (R 3.5.1)              
 rmarkdown   1.10       2018-06-11 CRAN (R 3.5.1)              
 rprojroot   1.3-2      2018-01-03 CRAN (R 3.5.1)              
 stats     * 3.5.1      2018-07-03 local                       
 stringi     1.2.3      2018-06-12 CRAN (R 3.5.1)              
 stringr     1.3.1      2018-05-10 CRAN (R 3.5.1)              
 tools       3.5.1      2018-07-03 local                       
 utils     * 3.5.1      2018-07-03 local                       
 withr       2.1.2      2018-03-15 CRAN (R 3.5.1)              
 yaml        2.1.19     2018-05-01 CRAN (R 3.5.1)              
```

**Comment by crsh** [comment] 2018-07-04 12:42
Thanks! Still no dice. I can spot two potential reasons from the session info, though. I'll try the latest R Studio and R versions as you are currently using newer ones than I am.

**Comment by crsh** [comment] 2018-07-04 12:47
Just as a quick follow-up: Did you install the additional [required LaTeX packages](https://github.com/crsh/papaja#requirements)?

**Comment by mischavk** [comment] 2018-07-04 13:07
Yes, all packages listed are installed and up to date.
Thanks for your efforts!

**Comment by mischavk** [comment] 2018-07-04 13:34
Ok, it works on my Windows system. Seems like it's an issue with texlive...

**Comment by crsh** [comment] 2018-07-04 14:02
Thanks for the feedback! Let me know if you can locate the source of the problem.

**Comment by mischavk** [comment] 2018-07-04 14:18
The problem seems to lie in the
```
\begin{table}[tbp]
```
command. As soon as I remove it, everything is fine. Any ideas on this?

**Comment by crsh** [comment] 2018-07-04 14:47
That's super weird, considering that that's a standard command. When you say you remove the command do you use `\begin{table}` instead?

**Comment by mischavk** [comment] 2018-07-04 19:29
No, I removed ``` \begin{table}```  and ```\end{table}``` altogether. Only then it works. It's the same on a different linux computer I've tried. Weird.

**Comment by crsh** [comment] 2018-07-04 20:09
I'm still scratching my head. From googling im getting that this may be related to labels. Could you try adding `lang: en-EN` to the YAML front matter and if that doesn't work eliminating all `_` from chunk labels and the table note? If that doesn't work, could you post the `.tex` file, if available?

**Comment by mischavk** [comment] 2018-07-04 21:04
It also works if change the output from ```papaja::apa6_pdf``` to ```pdf_document```.

**Comment by crsh** [comment] 2018-07-04 21:12
That's helpful, thanks. I diffed your file and mine and this came up:

<img width="1202" alt="bildschirmfoto 2018-07-04 um 22 55 49" src="https://user-images.githubusercontent.com/2195485/42293885-8b828eee-7fdd-11e8-9b00-7d40f7cd6a77.png">

The latter line is what's causing the problem. Now I'm completely clueless as to why the `\expandafter`s and `LastLTentrywidth` are removed. What version of `texlive` are you using?

At any rate, one of the `\expandafters` may be incorrect. I've removed it from the template. On the off chance that this helps, could you try again with the latest version?

**Comment by mischavk** [comment] 2018-07-04 22:19
Sadly, still the same problem. 
My ```texlive``` version is ```2015.20160320-1ubuntu0.1```.
I also tried MikTeX, did not change anything.
Hmmm..

**Comment by crsh** [comment] 2018-07-05 02:53
Hmm, `pandoc` could also be the source of the problem. What version are you currently using (`rmarkdown::pandoc_version()`)?

**Comment by mischavk** [comment] 2018-07-05 04:38
Good morning ;)
The ```pandoc``` version is 2.2.1

**Comment by mischavk** [comment] 2018-07-05 07:28
I've cut down the problem to the fact that it's the second ```\expandafter``` that need to be there.
If I change the line in my tex file to 

```\renewcommand{\efloat@iwrite}[1]{\immediate\expandafter\protected@write\csname efloat@post#1\endcsname{}}```

the compilation works.

**Comment by crsh** [comment] 2018-07-05 08:06
I've had problems with `pandoc` eliminating parts of the LaTeX code inserted into the preamble before. Now that RStudio ships with `pandoc` 2.2.1 I hope I can utilize the [`raw_attribute`](https://pandoc.org/MANUAL.html#extension-raw_attribute)-extension to get a handle on this problem. I'll work on this the next chance I get. Thanks for your efforts in debugging this issue.

**Comment by crsh** [comment] 2018-07-10 21:05
Okay, I *think* I have fixed this. `papaja` now checks to see whether the `pandoc` extension `raw_attribute` is available (i.e., `pandoc` version number is at least 2.0) and uses the extension to prevent random error such as the one documented here.

Could you give it a try (`devtools::install_github("crsh/papaja@devel")`) to see if that fixes the problem?

**Comment by mischavk** [comment] 2018-07-11 09:30
Yeah, it works!
Thank you very much! :)

**Closed** 2018-08-08 15:54 UTC
Labels: bug
