### ISSUE TITLE
Conflicting implementation of `labelled` class

### ISSUE THREAD

**Issue by andreifoldes** [crsh/papaja#199] opened 2018-04-04 00:47 UTC
Hello,

I discovered the following issue:
By default this runs smoothly

~~~r
library(papaja)
load('.../mixed_data.rdata')

recall_anova <- afex::aov_car(
  Recall ~ (Task * Valence * Dosage) + Error(Subject/(Task * Valence)) + Dosage
  , data = mixed_data
  , type = 3
)

recall_anova_results <- apa_print(recall_anova$aov, es = "pes")
~~~
however

~~~r
library(papaja)
library(tidyverse)

recall_anova <- afex::aov_car(
  Recall ~ (Task * Valence * Dosage) + Error(Subject/(Task * Valence)) + Dosage
  , data = mixed_data
  , type = 3
)

recall_anova_results <- apa_print(recall_anova$aov, es = "pes")
~~~

I get a Error: `x` and `labels` must be same type
If you switch the sequence library(tidyverse) library(papaja) then its Okay, but I think this could cause a lot of headache for people.

**Comment by crsh** [comment] 2018-04-09 16:30
Sorry, this may have been premature. Upon a closer look, I was unable to reproduce the problem. I had to install `tidyverse` so maybe updating your the package version may help? Either way, could you provide your `devtools::session_info()` to help pinpoint the problem?

**Comment by andreifoldes** [comment] 2018-04-12 16:37
Hi - I had to change my hard drive and on my fresh one I can't replicate the issue either, but I'm really curious now and will try looking at it with the old hard drive. In any case its probably not as big issue as I thought initially.

**Comment by CaroRowland** [comment] 2018-05-01 06:05
I've got the same problem . Here is the session info (note I'm on R 3.4.4. because I couldn't load afex with 3.5)

`> devtools::session_info()
Session info -------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 system   x86_64, mingw32             
 ui       RStudio (1.1.447)           
 language (EN)                        
 collate  English_United Kingdom.1252 
 tz       Europe/Berlin               
 date     2018-05-01                  

Packages -----------------------------------------------------------------------------------------------
 package      * version    date       source                      
 abind          1.4-5      2016-07-21 CRAN (R 3.4.1)              
 afex         * 0.20-2     2018-04-04 CRAN (R 3.4.4)              
 assertthat     0.2.0      2017-04-11 CRAN (R 3.4.4)              
 backports      1.1.2      2017-12-13 CRAN (R 3.4.3)              
 base         * 3.4.4      2018-03-15 local                       
 beeswarm     * 0.2.3      2016-04-25 CRAN (R 3.4.1)              
 bindr          0.1.1      2018-03-13 CRAN (R 3.4.4)              
 bindrcpp     * 0.2.2      2018-03-29 CRAN (R 3.4.4)              
 car            3.0-0      2018-04-02 CRAN (R 3.4.4)              
 carData        3.0-1      2018-03-28 CRAN (R 3.4.4)              
 cellranger     1.1.0      2016-07-27 CRAN (R 3.4.4)              
 coda           0.19-1     2016-12-08 CRAN (R 3.4.4)              
 codetools      0.2-15     2016-10-05 CRAN (R 3.4.4)              
 coin           1.2-2      2017-11-28 CRAN (R 3.4.4)              
 colorspace     1.3-2      2016-12-14 CRAN (R 3.4.4)              
 compiler       3.4.4      2018-03-15 local                       
 curl           3.2        2018-03-28 CRAN (R 3.4.4)              
 data.table     1.10.4-3   2017-10-27 CRAN (R 3.4.4)              
 datasets     * 3.4.4      2018-03-15 local                       
 devtools       1.13.5     2018-02-18 CRAN (R 3.4.3)              
 digest         0.6.15     2018-01-28 CRAN (R 3.4.3)              
 dplyr        * 0.7.4      2017-09-28 CRAN (R 3.4.3)              
 emmeans      * 1.1.3      2018-04-01 CRAN (R 3.4.4)              
 estimability   1.3        2018-02-11 CRAN (R 3.4.3)              
 evaluate       0.10.1     2017-06-24 CRAN (R 3.4.4)              
 forcats        0.3.0      2018-02-19 CRAN (R 3.4.4)              
 foreign        0.8-69     2017-06-22 CRAN (R 3.4.4)              
 ggplot2        2.2.1      2016-12-30 CRAN (R 3.4.4)              
 git2r          0.21.0     2018-01-04 CRAN (R 3.4.4)              
 glue           1.2.0      2017-10-29 CRAN (R 3.4.4)              
 graphics     * 3.4.4      2018-03-15 local                       
 grDevices    * 3.4.4      2018-03-15 local                       
 grid           3.4.4      2018-03-15 local                       
 gtable         0.2.0      2016-02-26 CRAN (R 3.4.4)              
 haven          1.1.1      2018-01-18 CRAN (R 3.4.4)              
 htmltools      0.3.6      2017-04-28 CRAN (R 3.4.4)              
 httr           1.3.1      2017-08-20 CRAN (R 3.4.4)              
 knitr          1.20       2018-02-20 CRAN (R 3.4.4)              
 lattice        0.20-35    2017-03-25 CRAN (R 3.4.4)              
 lazyeval       0.2.1      2017-10-29 CRAN (R 3.4.4)              
 lme4         * 1.1-17     2018-04-03 CRAN (R 3.4.4)              
 lmerTest       3.0-1      2018-04-23 CRAN (R 3.4.4)              
 magrittr       1.5        2014-11-22 CRAN (R 3.4.4)              
 MASS           7.3-49     2018-02-23 CRAN (R 3.4.4)              
 Matrix       * 1.2-12     2017-11-30 CRAN (R 3.4.4)              
 memoise        1.1.0      2017-04-21 CRAN (R 3.4.4)              
 methods      * 3.4.4      2018-03-15 local                       
 minqa          1.2.4      2014-10-09 CRAN (R 3.4.4)              
 modeltools     0.2-21     2013-09-02 CRAN (R 3.4.1)              
 multcomp       1.4-8      2017-11-08 CRAN (R 3.4.4)              
 munsell        0.4.3      2016-02-13 CRAN (R 3.4.4)              
 mvtnorm        1.0-7      2018-01-26 CRAN (R 3.4.3)              
 nlme           3.1-131.1  2018-02-16 CRAN (R 3.4.4)              
 nloptr         1.0.4      2017-08-22 CRAN (R 3.4.4)              
 numDeriv       2016.8-1   2016-08-27 CRAN (R 3.4.1)              
 openxlsx       4.0.17     2017-03-23 CRAN (R 3.4.3)              
 papaja       * 0.1.0.9709 2018-05-01 Github (crsh/papaja@f41a7cc)
 parallel       3.4.4      2018-03-15 local                       
 pillar         1.2.2      2018-04-26 CRAN (R 3.4.4)              
 pkgconfig      2.0.1      2017-03-21 CRAN (R 3.4.4)              
 plyr           1.8.4      2016-06-08 CRAN (R 3.4.4)              
 R6             2.2.2      2017-06-17 CRAN (R 3.4.4)              
 Rcpp           0.12.16    2018-03-13 CRAN (R 3.4.4)              
 readxl         1.1.0      2018-04-20 CRAN (R 3.4.4)              
 reshape2       1.4.3      2017-12-11 CRAN (R 3.4.4)              
 rio            0.5.10     2018-03-29 CRAN (R 3.4.4)              
 rlang          0.2.0      2018-02-20 CRAN (R 3.4.4)              
 rmarkdown      1.9        2018-03-01 CRAN (R 3.4.4)              
 rprojroot      1.3-2      2018-01-03 CRAN (R 3.4.4)              
 sandwich       2.4-0      2017-07-26 CRAN (R 3.4.4)              
 scales         0.5.0      2017-08-24 CRAN (R 3.4.4)              
 splines        3.4.4      2018-03-15 local                       
 stats        * 3.4.4      2018-03-15 local                       
 stats4         3.4.4      2018-03-15 local                       
 stringi        1.1.7      2018-03-12 CRAN (R 3.4.4)              
 stringr        1.3.0      2018-02-19 CRAN (R 3.4.4)              
 survival       2.41-3     2017-04-04 CRAN (R 3.4.4)              
 TH.data        1.0-8      2017-01-23 CRAN (R 3.4.4)              
 tibble         1.4.2      2018-01-22 CRAN (R 3.4.4)              
 tools          3.4.4      2018-03-15 local                       
 utils        * 3.4.4      2018-03-15 local                       
 withr          2.1.2      2018-03-15 CRAN (R 3.4.4)              
 xtable         1.8-2      2016-02-05 CRAN (R 3.4.4)              
 yaml           2.1.18     2018-03-08 CRAN (R 3.4.4)              
 zoo            1.8-1      2018-01-08 CRAN (R 3.4.4)  `

**Comment by mariusbarth** [comment] 2018-05-01 09:30
Hi @CaroRowland,
what exactly is the code that produces an error and what error message do you get?

**Comment by CaroRowland** [comment] 2018-05-01 09:43
Hi, I'm just running the code through, in order, just as written in the example.Rmd, which I downloaded from github.  R gets stuck here with the error message "Error: `x` and `labels` must be same type"

``{r echo = TRUE}
recall_anova <- afex::aov_car(
  Recall ~ (Task * Valence * Dosage) + Error(Subject/(Task * Valence)) + Dosage
  , data = mixed_data
  , type = 3
)
recall_anova_results <- apa_print(recall_anova, es = "pes")
recall_anova_results_p <- apa_print(recall_anova, es = "pes", in_paren = TRUE)
``

**Comment by CaroRowland** [comment] 2018-05-01 09:45
I also sometimes get the same error when running the beeplot code but sometimes this work:

````{r beeplot, fig.cap = "Bee plot of the example data set. Small points represent individual observations, large points represent means, and error bars represent 95% confidence intervals.", echo = TRUE, dev.args = list(bg = 'white')}
apa_beeplot(
  mixed_data
  , id = "Subject"
  , dv = "Recall"
  , factors = c("Task", "Valence", "Dosage")
  , dispersion = conf_int
  , ylim = c(0, 30)
  , las = 1
  , args_points = list(cex = 1.5)
  , args_arrows = list(length = 0.025)
)
``

**Comment by PatrickLaflamme** [comment] 2018-05-10 17:57
I'm also getting the same problem, but when trying to use `apa_print` with a summary.lm object. session info below.

I've spent some time trying to find a reproducible example, but I can't seem to find one. It'll work over and over, until suddenly it'll throw the `Error: 'x' and 'labels' must be same type` error, after which it won't work at all.

```
Session info -----------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.0 (2018-04-23)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.447)           
 language (EN)                        
 collate  en_CA.UTF-8                 
 tz       America/Vancouver           
 date     2018-05-10                  

Packages ---------------------------------------------------------------------------------------------
 package    * version    date       source                        
 abind        1.4-5      2016-07-21 CRAN (R 3.5.0)                
 assertthat   0.2.0      2017-04-11 CRAN (R 3.5.0)                
 base       * 3.5.0      2018-04-24 local                         
 bindr        0.1.1      2018-03-13 CRAN (R 3.5.0)                
 bindrcpp   * 0.2.2      2018-03-29 CRAN (R 3.5.0)                
 boot       * 1.3-20     2017-08-06 CRAN (R 3.5.0)                
 broom        0.4.4      2018-03-29 cran (@0.4.4)                 
 car        * 3.0-0      2018-04-02 CRAN (R 3.5.0)                
 carData    * 3.0-1      2018-03-28 CRAN (R 3.5.0)                
 cellranger   1.1.0      2016-07-27 CRAN (R 3.5.0)                
 colorspace   1.3-2      2016-12-14 CRAN (R 3.5.0)                
 compiler     3.5.0      2018-04-24 local                         
 curl         3.2        2018-03-28 CRAN (R 3.5.0)                
 data.table   1.11.2     2018-05-08 CRAN (R 3.5.0)                
 datasets   * 3.5.0      2018-04-24 local                         
 devtools     1.13.5     2018-02-18 CRAN (R 3.5.0)                
 digest       0.6.15     2018-01-28 CRAN (R 3.5.0)                
 dplyr      * 0.7.4      2017-09-28 CRAN (R 3.5.0)                
 fabs       * 0.1        2018-05-09 Github (jbiesanz/fabs@b522e57)
 forcats      0.3.0      2018-02-19 CRAN (R 3.5.0)                
 foreign      0.8-70     2017-11-28 CRAN (R 3.5.0)                
 ggplot2    * 2.2.1      2016-12-30 CRAN (R 3.5.0)                
 ggridges     0.5.0      2018-04-05 CRAN (R 3.5.0)                
 glue         1.2.0      2017-10-29 CRAN (R 3.5.0)                
 graphics   * 3.5.0      2018-04-24 local                         
 grDevices  * 3.5.0      2018-04-24 local                         
 grid         3.5.0      2018-04-24 local                         
 gtable       0.2.0      2016-02-26 CRAN (R 3.5.0)                
 haven        1.1.1      2018-01-18 CRAN (R 3.5.0)                
 heplots    * 1.3-5      2018-04-03 CRAN (R 3.5.0)                
 knitr      * 1.20       2018-02-20 CRAN (R 3.5.0)                
 labeling     0.3        2014-08-23 CRAN (R 3.5.0)                
 lattice      0.20-35    2017-03-25 CRAN (R 3.5.0)                
 lazyeval     0.2.1      2017-10-29 CRAN (R 3.5.0)                
 magrittr     1.5        2014-11-22 CRAN (R 3.5.0)                
 MASS       * 7.3-50     2018-04-30 CRAN (R 3.5.0)                
 Matrix     * 1.2-14     2018-04-13 CRAN (R 3.5.0)                
 memoise      1.1.0      2017-04-21 CRAN (R 3.5.0)                
 methods    * 3.5.0      2018-04-24 local                         
 mnormt       1.5-5      2016-10-15 cran (@1.5-5)                 
 munsell      0.4.3      2016-02-13 CRAN (R 3.5.0)                
 nlme         3.1-137    2018-04-07 CRAN (R 3.5.0)                
 norm       * 1.0-9.5    2013-02-28 cran (@1.0-9.5)               
 openxlsx     4.0.17     2017-03-23 CRAN (R 3.5.0)                
 papaja     * 0.1.0.9709 2018-05-10 Github (crsh/papaja@f41a7cc)  
 parallel   * 3.5.0      2018-04-24 local                         
 pillar       1.2.2      2018-04-26 CRAN (R 3.5.0)                
 pkgconfig    2.0.1      2017-03-21 CRAN (R 3.5.0)                
 plyr         1.8.4      2016-06-08 CRAN (R 3.5.0)                
 psych        1.8.4      2018-05-06 cran (@1.8.4)                 
 purrr        0.2.4      2017-10-18 CRAN (R 3.5.0)                
 R6           2.2.2      2017-06-17 CRAN (R 3.5.0)                
 Rcpp         0.12.16    2018-03-13 CRAN (R 3.5.0)                
 readxl       1.1.0      2018-04-20 CRAN (R 3.5.0)                
 reshape2     1.4.3      2017-12-11 CRAN (R 3.5.0)                
 rio          0.5.10     2018-03-29 CRAN (R 3.5.0)                
 rlang        0.2.0      2018-02-20 CRAN (R 3.5.0)                
 scales       0.5.0      2017-08-24 CRAN (R 3.5.0)                
 stats      * 3.5.0      2018-04-24 local                         
 stringi      1.2.2      2018-05-02 CRAN (R 3.5.0)                
 stringr      1.3.0      2018-02-19 CRAN (R 3.5.0)                
 tibble       1.4.2      2018-01-22 CRAN (R 3.5.0)                
 tidyr        0.8.0      2018-01-29 CRAN (R 3.5.0)                
 tools        3.5.0      2018-04-24 local                         
 utils      * 3.5.0      2018-04-24 local                         
 withr        2.1.2      2018-03-15 CRAN (R 3.5.0)                
 yaml         2.1.19     2018-05-01 CRAN (R 3.5.0) 
```

**Comment by PatrickLaflamme** [comment] 2018-05-14 17:08
I've managed to fully isolate the problem, at least on my end. It seems that the `car` package needs to be loaded before the `papaja` package. 

This runs fine:

```
library(mvtnorm)
library(car)
library(papaja)

dataSet <- rmvnorm(100, sigma=diag(c(1,1,1)))
dataSet <- data.frame(dataSet)

model <- lm(X1 ~ X2*X3, data = dataSet)

car::ncvTest(model)

apa_lm <- apa_print(model)
```

but this does not:

```
library(mvtnorm)
library(papaja)
library(car)

dataSet <- rmvnorm(100, sigma=diag(c(1,1,1)))
dataSet <- data.frame(dataSet)

model <- lm(X1 ~ X2*X3, data = dataSet)

car::ncvTest(model)

apa_lm <- apa_print(model)
```

R doesn't give any warnings about functions being overwritten, so I'm not 100% why the order of the loading matters, but it clearly does.

**Comment by mariusbarth** [comment] 2018-05-15 12:47
Hi @PatrickLaflamme, 

thanks for your input. With the help of your example, I could narrow down the problem a bit more. The problem seems to stem from different implementations of the S3 class `labelled`: We adopted the implementation from the `Hmisc` package, but the `haven` package (which is attached when `car` is loaded) uses another implementation that is incompatible. Therefore, I opened an issue at https://github.com/tidyverse/haven/issues/374 -- let's see if the developers have a nice idea how to implement compatibility between the `Hmisc` and the haven (i.e. tidyverse) worlds.

Until we found a good and versatile solution, I can only recommend to load `papaja` last. I'm keeping an eye on this issue and will keep you posted.

**Comment by JimGrange** [comment] 2018-06-03 08:43
I have run into this issue, too. I do not have all of the tidyverse loaded (just ggplot2 and dplyr). I also load papaja last and the error remains. Knitting throws the error, but manually walking through the code in the script works fine. 

Here is session info:

```{r
Session info -----------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.0 (2018-04-23)
 system   x86_64, mingw32             
 ui       RStudio (1.1.447)           
 language (EN)                        
 collate  English_United Kingdom.1252 
 tz       Europe/London               
 date     2018-06-03                  

Packages ---------------------------------------------------------------------------------
 package        * version    date       source                            
 abind            1.4-5      2016-07-21 CRAN (R 3.5.0)                    
 afex           * 0.20-2     2018-04-04 CRAN (R 3.5.0)                    
 assertthat       0.2.0      2017-04-11 CRAN (R 3.5.0)                    
 base           * 3.5.0      2018-04-23 local                             
 base64enc        0.1-3      2015-07-28 CRAN (R 3.5.0)                    
 bayesplot        1.5.0      2018-03-30 CRAN (R 3.5.0)                    
 bindr            0.1.1      2018-03-13 CRAN (R 3.5.0)                    
 bindrcpp       * 0.2.2      2018-03-29 CRAN (R 3.5.0)                    
 bridgesampling   0.4-0      2017-12-19 CRAN (R 3.5.0)                    
 brms           * 2.2.0      2018-04-13 CRAN (R 3.5.0)                    
 Brobdingnag      1.2-5      2018-03-18 CRAN (R 3.5.0)                    
 car              3.0-0      2018-04-02 CRAN (R 3.5.0)                    
 carData          3.0-1      2018-03-28 CRAN (R 3.5.0)                    
 cellranger       1.1.0      2016-07-27 CRAN (R 3.5.0)                    
 clipr            0.4.0      2017-11-03 CRAN (R 3.5.0)                    
 clisymbols       1.2.0      2017-05-21 CRAN (R 3.5.0)                    
 coda             0.19-1     2016-12-08 CRAN (R 3.5.0)                    
 codetools        0.2-15     2016-10-05 CRAN (R 3.5.0)                    
 coin             1.2-2      2017-11-28 CRAN (R 3.5.0)                    
 colorspace       1.3-2      2016-12-14 CRAN (R 3.5.0)                    
 colourpicker     1.0        2017-09-27 CRAN (R 3.5.0)                    
 compiler         3.5.0      2018-04-23 local                             
 crosstalk        1.0.0      2016-12-21 CRAN (R 3.5.0)                    
 curl             3.2        2018-03-28 CRAN (R 3.5.0)                    
 data.table       1.11.0     2018-05-01 CRAN (R 3.5.0)                    
 datasets       * 3.5.0      2018-04-23 local                             
 devtools         1.13.5     2018-02-18 CRAN (R 3.5.0)                    
 digest           0.6.15     2018-01-28 CRAN (R 3.5.0)                    
 dplyr          * 0.7.4      2017-09-28 CRAN (R 3.5.0)                    
 DT               0.4        2018-01-30 CRAN (R 3.5.0)                    
 dygraphs         1.1.1.4    2017-01-04 CRAN (R 3.5.0)                    
 emmeans        * 1.1.3      2018-04-01 CRAN (R 3.5.0)                    
 estimability     1.3        2018-02-11 CRAN (R 3.5.0)                    
 forcats          0.3.0      2018-02-19 CRAN (R 3.5.0)                    
 foreign          0.8-70     2017-11-28 CRAN (R 3.5.0)                    
 ggplot2        * 2.2.1      2016-12-30 CRAN (R 3.5.0)                    
 ggridges         0.5.0      2018-04-05 CRAN (R 3.5.0)                    
 glue             1.2.0      2017-10-29 CRAN (R 3.5.0)                    
 graphics       * 3.5.0      2018-04-23 local                             
 grDevices      * 3.5.0      2018-04-23 local                             
 grid             3.5.0      2018-04-23 local                             
 gridExtra        2.3        2017-09-09 CRAN (R 3.5.0)                    
 gtable           0.2.0      2016-02-26 CRAN (R 3.5.0)                    
 gtools           3.5.0      2015-05-29 CRAN (R 3.5.0)                    
 haven            1.1.1      2018-01-18 CRAN (R 3.5.0)                    
 htmltools        0.3.6      2017-04-28 CRAN (R 3.5.0)                    
 htmlwidgets      1.2        2018-04-19 CRAN (R 3.5.0)                    
 httpuv           1.4.2      2018-05-03 CRAN (R 3.5.0)                    
 igraph           1.2.1      2018-03-10 CRAN (R 3.5.0)                    
 inline           0.3.14     2015-04-13 CRAN (R 3.5.0)                    
 knitr            1.20       2018-02-20 CRAN (R 3.5.0)                    
 later            0.7.2      2018-05-01 CRAN (R 3.5.0)                    
 lattice          0.20-35    2017-03-25 CRAN (R 3.5.0)                    
 lazyeval         0.2.1      2017-10-29 CRAN (R 3.5.0)                    
 lme4           * 1.1-17     2018-04-03 CRAN (R 3.5.0)                    
 lmerTest         3.0-1      2018-04-23 CRAN (R 3.5.0)                    
 loo              2.0.0      2018-04-11 CRAN (R 3.5.0)                    
 magrittr         1.5        2014-11-22 CRAN (R 3.5.0)                    
 markdown         0.8        2017-04-20 CRAN (R 3.5.0)                    
 MASS             7.3-49     2018-02-23 CRAN (R 3.5.0)                    
 Matrix         * 1.2-14     2018-04-13 CRAN (R 3.5.0)                    
 matrixStats      0.53.1     2018-02-11 CRAN (R 3.5.0)                    
 memoise          1.1.0      2017-04-21 CRAN (R 3.5.0)                    
 methods        * 3.5.0      2018-04-23 local                             
 mime             0.5        2016-07-07 CRAN (R 3.5.0)                    
 miniUI           0.1.1      2016-01-15 CRAN (R 3.5.0)                    
 minqa            1.2.4      2014-10-09 CRAN (R 3.5.0)                    
 modeltools       0.2-21     2013-09-02 CRAN (R 3.5.0)                    
 multcomp         1.4-8      2017-11-08 CRAN (R 3.5.0)                    
 munsell          0.4.3      2016-02-13 CRAN (R 3.5.0)                    
 mvtnorm          1.0-7      2018-01-25 CRAN (R 3.5.0)                    
 nlme             3.1-137    2018-04-07 CRAN (R 3.5.0)                    
 nloptr           1.0.4      2017-08-22 CRAN (R 3.5.0)                    
 numDeriv         2016.8-1   2016-08-27 CRAN (R 3.5.0)                    
 openxlsx         4.0.17     2017-03-23 CRAN (R 3.5.0)                    
 papaja         * 0.1.0.9709 2018-05-05 Github (crsh/papaja@f41a7cc)      
 parallel         3.5.0      2018-04-23 local                             
 pillar           1.2.2      2018-04-26 CRAN (R 3.5.0)                    
 pkgconfig        2.0.1      2017-03-21 CRAN (R 3.5.0)                    
 plyr             1.8.4      2016-06-08 CRAN (R 3.5.0)                    
 promises         1.0.1      2018-04-13 CRAN (R 3.5.0)                    
 R6               2.2.2      2017-06-17 CRAN (R 3.5.0)                    
 Rcpp           * 0.12.16    2018-03-13 CRAN (R 3.5.0)                    
 readxl           1.1.0      2018-04-20 CRAN (R 3.5.0)                    
 reshape2         1.4.3      2017-12-11 CRAN (R 3.5.0)                    
 rio              0.5.10     2018-03-29 CRAN (R 3.5.0)                    
 rlang            0.2.0      2018-02-20 CRAN (R 3.5.0)                    
 rsconnect        0.8.8      2018-03-09 CRAN (R 3.5.0)                    
 rstan            2.17.3     2018-01-20 CRAN (R 3.5.0)                    
 rstantools       1.5.0      2018-04-17 CRAN (R 3.5.0)                    
 sandwich         2.4-0      2017-07-26 CRAN (R 3.5.0)                    
 scales           0.5.0      2017-08-24 CRAN (R 3.5.0)                    
 sessioninfo      1.0.1.9000 2018-06-03 Github (r-lib/sessioninfo@c871d01)
 shiny            1.0.5      2017-08-23 CRAN (R 3.5.0)                    
 shinyjs          1.0        2018-01-08 CRAN (R 3.5.0)                    
 shinystan        2.5.0      2018-05-01 CRAN (R 3.5.0)                    
 shinythemes      1.1.1      2016-10-12 CRAN (R 3.5.0)                    
 splines          3.5.0      2018-04-23 local                             
 StanHeaders      2.17.2     2018-01-20 CRAN (R 3.5.0)                    
 stats          * 3.5.0      2018-04-23 local                             
 stats4           3.5.0      2018-04-23 local                             
 stringi          1.2.2      2018-05-02 CRAN (R 3.5.0)                    
 stringr          1.3.1      2018-05-10 CRAN (R 3.5.0)                    
 survival         2.41-3     2017-04-04 CRAN (R 3.5.0)                    
 TH.data          1.0-8      2017-01-23 CRAN (R 3.5.0)                    
 threejs          0.3.1      2017-08-13 CRAN (R 3.5.0)                    
 tibble           1.4.2      2018-01-22 CRAN (R 3.5.0)                    
 tools            3.5.0      2018-04-23 local                             
 trimr          * 1.0.1.9000 2018-05-05 Github (JimGrange/trimr@1ca3115)  
 utils          * 3.5.0      2018-04-23 local                             
 withr            2.1.2      2018-03-15 CRAN (R 3.5.0)                    
 xtable           1.8-2      2016-02-05 CRAN (R 3.5.0)                    
 xts              0.10-2     2018-03-14 CRAN (R 3.5.0)                    
 yaml             2.1.19     2018-05-01 CRAN (R 3.5.0)                    
 zoo              1.8-1      2018-01-08 CRAN (R 3.5.0)  

```

**Comment by Zweckoptimismus** [comment] 2018-06-04 07:35
Guys, as far as I understand Hadley's post, there won't be a fast fix for this, right? 
I'm having the same issue when loading the "tableone" package, but my session info also includes haven. My problem occured as follows: 
I import data using Hmisc::spss.get()
The str() of the data is fine, even with library(tableone). 
But when I want to CreateTableOne() on the data, I get the same error as above AND afterwards, the str() of my data returns the same error. 
Detaching Hmisc directly after data import did not fix the problem, unfortunately. 
It's a pity, because I need all these packages so badly. :-)

**Comment by crsh** [comment] 2018-06-04 13:20
@JimGrange Have you tried loading `Hmisc` and `papaja` after the package that loads `haven` as a dependency, as per @craddm?

This is situation is really a mess. Detaching a package usually doesn't solve the issue because the registered S3 methods are not removed when a package is detached. The S3 methods in `haven` are what is causing the problem here. Seeing that this is a pressing issue and it seems it might be a while until a fix in `haven` is available, @mariusbarth has agreed to provide a pull request with a temporary fix soon. I'll announce it here, as soon as it's merged into the development branch.

**Comment by Zweckoptimismus** [comment] 2018-06-04 13:58
Thank you very much for letting us know, @crsh !

As a reaction to your answer to @JimGrange , I re-checked my script. Here's the session info, no haven in there: 

Session info ---------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.0 (2018-04-23)
 system   x86_64, mingw32             
 ui       RStudio (1.1.453)           
 language (EN)                        
 collate  German_Germany.1252         
 tz       Europe/Berlin               
 date     2018-06-04                  

Packages -------------------------------------------------------------------------------------------------------
 package      * version date       source        
 acepack        1.4.1   2016-10-29 CRAN (R 3.5.0)
 backports      1.1.2   2017-12-13 CRAN (R 3.5.0)
 base         * 3.5.0   2018-04-23 local         
 base64enc      0.1-3   2015-07-28 CRAN (R 3.5.0)
 checkmate      1.8.5   2017-10-24 CRAN (R 3.5.0)
 cluster        2.0.7-1 2018-04-13 CRAN (R 3.5.0)
 colorspace     1.3-2   2016-12-14 CRAN (R 3.5.0)
 compiler       3.5.0   2018-04-23 local         
 data.table     1.11.4  2018-05-27 CRAN (R 3.5.0)
 datasets     * 3.5.0   2018-04-23 local         
 devtools       1.13.5  2018-02-18 CRAN (R 3.5.0)
 digest         0.6.15  2018-01-28 CRAN (R 3.5.0)
 foreign        0.8-70  2017-11-28 CRAN (R 3.5.0)
 Formula      * 1.2-3   2018-05-03 CRAN (R 3.5.0)
 ggplot2      * 2.2.1   2016-12-30 CRAN (R 3.5.0)
 graphics     * 3.5.0   2018-04-23 local         
 grDevices    * 3.5.0   2018-04-23 local         
 grid           3.5.0   2018-04-23 local         
 gridExtra      2.3     2017-09-09 CRAN (R 3.5.0)
 gtable         0.2.0   2016-02-26 CRAN (R 3.5.0)
 Hmisc        * 4.1-1   2018-01-03 CRAN (R 3.5.0)
 htmlTable      1.12    2018-05-26 CRAN (R 3.5.0)
 htmltools      0.3.6   2017-04-28 CRAN (R 3.5.0)
 htmlwidgets    1.2     2018-04-19 CRAN (R 3.5.0)
 knitr          1.20    2018-02-20 CRAN (R 3.5.0)
 lattice      * 0.20-35 2017-03-25 CRAN (R 3.5.0)
 latticeExtra   0.6-28  2016-02-09 CRAN (R 3.5.0)
 lazyeval       0.2.1   2017-10-29 CRAN (R 3.5.0)
 magrittr       1.5     2014-11-22 CRAN (R 3.5.0)
 Matrix         1.2-14  2018-04-13 CRAN (R 3.5.0)
 memoise        1.1.0   2017-04-21 CRAN (R 3.5.0)
 methods      * 3.5.0   2018-04-23 local         
 munsell        0.4.3   2016-02-13 CRAN (R 3.5.0)
 nnet           7.3-12  2016-02-02 CRAN (R 3.5.0)
 pillar         1.2.3   2018-05-25 CRAN (R 3.5.0)
 plyr           1.8.4   2016-06-08 CRAN (R 3.5.0)
 RColorBrewer   1.1-2   2014-12-07 CRAN (R 3.5.0)
 Rcpp           0.12.17 2018-05-18 CRAN (R 3.5.0)
 rlang          0.2.0   2018-02-20 CRAN (R 3.5.0)
 rpart          4.1-13  2018-02-23 CRAN (R 3.5.0)
 rstudioapi     0.7     2017-09-07 CRAN (R 3.5.0)
 scales         0.5.0   2017-08-24 CRAN (R 3.5.0)
 splines        3.5.0   2018-04-23 local         
 stats        * 3.5.0   2018-04-23 local         
 stringi        1.1.7   2018-03-12 CRAN (R 3.5.0)
 stringr        1.3.1   2018-05-10 CRAN (R 3.5.0)
 survey         3.33-2  2018-03-13 CRAN (R 3.5.0)
 survival     * 2.41-3  2017-04-04 CRAN (R 3.5.0)
 tableone     * 0.9.3   2018-04-29 CRAN (R 3.5.0)
 tibble         1.4.2   2018-01-22 CRAN (R 3.5.0)
 tools          3.5.0   2018-04-23 local         
 utils        * 3.5.0   2018-04-23 local         
 withr          2.1.2   2018-03-15 CRAN (R 3.5.0)
 yaml           2.1.19  2018-05-01 CRAN (R 3.5.0)

Directly after that, I use spss.get(), the str() of the data is fine. 
After a call to CreateTableOne(), I get an error and the str() of the data is broken. 
Switching the order of package loading (Hmisc-tableone, tableone-Hmisc) didn't change a thing. 
Instead, I now apply a pretty ugly workaround including a separate Project to create the Table 1. 
Thanks for keeping us posted!

**Comment by crsh** [comment] 2018-06-04 18:32
`haven` is a second order import. `tableone` imports `labelled` which imports `haven`. Unless I'm mistaken, if you display the session info in the document that produces this error it should include `haven`.

**Comment by crsh** [comment] 2018-06-05 16:06
Okay, we have proposed temporary fix for this. Could you try installing that version (`devtools::install_github("crsh/papaja@labelled-fix")`) and let me know if it works? Once, we have confirmation that this resolves the issue, I'll merge the branch into `devel` and then into `master` as soon as possible.

**Comment by danielschad** [comment] 2018-06-06 13:08
Hi, I just encountered this error. Changing the order of package loading did not help. Now I downloaded the fix, and everything works smoothly. Looks great for me. Thanks!

**Comment by Zweckoptimismus** [comment] 2018-06-06 14:04
So sorry I couldn't answer earlier. I just tried it and it seems to have fixed the issue for me! Thank you so much!!

**Comment by crsh** [comment] 2018-06-08 13:38
Great! I've merged the fix into the development branch (`devtools::install_github("crsh/papaja@devel")`). Thanks again for reporting and helping to diagnose this issue.

**Closed** 2018-08-08 16:07 UTC
