### ISSUE TITLE
error in apa_table with tibble from loo object

### ISSUE THREAD

**Issue by bnicenboim** [crsh/papaja#320] opened 2019-10-07 07:32 UTC
**Describe the bug**
`apa_table` gives an error with a tibble I created from a matrix (that was the output of loo::comparison)

**To Reproduce**
This is the tibble object giving troubles
```
structure(list(Models = c("log Cloze prob.", "Cloze prob.", "factorial predictor"), `Difference in elpd` = structure(c(0, -6.84577291430994, -12.7581782378967), class = c("compare.loo", "matrix", "old_compare.loo")), SE = structure(c(0,3.59188997088888, 6.84232412683554), class = c("compare.loo", "matrix", "old_compare.loo"))), class = c("tbl_df", "tbl", "data.frame"), row.names = c(NA, -3L)) %>% apa_table()
```
And this is the error
```
Error in seq_len(ncols) : 
  argument must be coercible to non-negative integer
In addition: Warning message:
In seq_len(ncols) : first element used of 'length.out' argument
```
I generated that object by converting a `loo` comparison matrix into a tibble

**Expected behavior**
I would expect a regular apa_table

**Comment by bnicenboim** [comment] 2019-10-07 07:51
Ok, I'm pretty sure that the problem is that the numbers have another class besides `numeric`, if I force the columns to be numeric with `as.numeric`, I can pipe it into `apa_tabla`. It still might be a good idea to fix this behavior.

**Comment by crsh** [comment] 2019-10-21 20:07
Hi Bruno, thanks for reporting this. The issue seems to be that each numeric column of this `tibble` is of class `matrix` (among other things). This causes all sorts of S3-related confusion. In fact you get the same error when you pipe this object into `summary()`. I wonder whether this is intended behavior from the `loo` side. Do you have a particular reason for coverting the object into a `tibble`? Have you tried, whether you get the same error when converting the `loo`-output to a regular `data.frame` or leaving it as is?

**Comment by bnicenboim** [comment] 2019-10-23 13:23
Ok, you're right, it's something weird with the conversion from matrix to tibble. The data frame works just fine. I should report it to tibble.
Sorry to bother you with this. At most you can make a more informative error message on your side, if not feel free to close the issue.

**Comment by crsh** [comment] 2019-10-24 07:41
A better error message would be good, I agree. However, the S3 dispatch mess caused by this makes it very hard to catch this problem. For now, I'll hope this gets fixed on the `tibble` end. If you open an issue, could you link to it here, so I can follow the developments?

**Closed** 2019-11-21 20:59 UTC
Labels: unrelated
