### ISSUE TITLE
Permitting echo = TRUE in appendices

### ISSUE THREAD

**Issue by stonegold546** [crsh/papaja#249] opened 2018-09-26 14:52 UTC
When I set `echo = TRUE`in an appendix, I get an error when I knit the document.

The alternative I am using is to save the code in a script, read the script and print out the script without echoing the code that does this.

I'm working on a manuscript, and I'd like to provide some syntax in the Appendix.

Thanks.

**Comment by crsh** [comment] 2018-10-22 20:42
Hi James, sorry for the late reply. Could you provide a minimal reproducible example (e.g., R Markdown files) so I can dig into this?

**Comment by stonegold546** [comment] 2018-10-24 12:53
Thanks for the reply.

My papaja version is 0.1.0.9842

I create a new papaja markdown file and permit two appendices:

```
---
documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
appendix          :
  - "appendix_a.Rmd"
  - "appendix_b.Rmd"
---
```

Then in appendix_a.Rmd, all I have is the code chunk with:

```
```{r echo = TRUE}
rnorm(50)
```

When I knit, I get the error message:

output file: trial.knit.md

! LaTeX Error: Environment Shaded undefined.

Error: Failed to compile trial.tex. See trial.log for more info.
Execution halted

If I drop `echo = TRUE` from my code chunk, it knits fine.

Is this enough to reproduce the problem? Thanks.

**Comment by crsh** [comment] 2018-10-24 18:30
Thanks, I'll look into it, but it may take a little while.

**Comment by crsh** [comment] 2018-11-27 10:08
Wow, I into this for quite a while yesterday and I haven't found a fix for this. Basically, the problem is that the appendix is rendered separately from the main document. When `pandoc` creates the TeX file for the main document it checks whether there are any code chunks to be displayed and if so inserts the definition of some LaTeX environments to display the coded (among them `Shaded` as mentioned in the error message). If the main document does not contain code chunks, the environment definitions are omitted. Now, if the appendix uses `Shaded`, you get the error above.

I haven't found a way to force `pandoc` to include the definitions, so here are some suggestions for quick fixes.

1. The simplest option is to display at least one code chunk (set `echo = TRUE` for at least one chunk) in the main document. This way, the LaTeX environment definitions are added to the document preamble and also work in the appendix.

2. You could also manually include the needed LaTeX environment definitions for the desired highlighting theme in the preamble. This requires that you create a TeX file with the definitions and add it as `header-include`. See [this StackOverflow question](https://stackoverflow.com/a/51649399/914024) for detailed instructions.

**Comment by stonegold546** [comment] 2018-11-27 16:13
Thanks for taking the time to look into this! Both the options you recommend work perfectly for me. Thanks!!

**Comment by jooyoungseo** [comment] 2019-01-20 00:44
@crsh,

Would you mind adding the following LaTeX code in `resources/apa6_header_includes.tex` as a package-wise for papaja users without having to use extra line for header tex?

That resolves the Shaded issue.

```
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
```

**Comment by crsh** [comment] 2019-01-20 20:40
Thanks for the suggestion, but I'm afraid it will be a little more complicated than this. The LaTeX code above is what `pandoc` adds automatically if it finds a displayed code chunk in the document. The exact form of this depends on the selected syntax highlighting style. If I add this to the header includes it will be in the TeX document twice and conflict with what `pandoc` adds in various ways. So I think this needs to be solved programmatically.

**Comment by crsh** [comment] 2021-12-15 23:15
I just submitted a PR that should resolve this issue. If you would like to try it out install via `remotes::install_github("crsh/papaja@crsh/issue496")` and let me know if it works.

**Comment by crsh** [comment] 2022-07-04 19:37
Closing, because I think this has been resolved by the mentioned PR.

**Closed by crsh** 2022-07-04 19:37 UTC
Labels: enhancement, more-information-needed
