### ISSUE TITLE
apa_print gives error message for lm

### ISSUE THREAD

**Issue by henda52** [crsh/papaja#374] opened 2020-05-29 10:23 UTC
**Describe the bug**
I got an error message when I try to knit a papaja markdown regarding apa_print.
I have a regression analysis where the results are saved in lm_out. I then try to use
apa_lm <- apa_print(lm_out) but I got the error message:
Error in UseMethod("apa_print", x) : no applicable method for 'apa_print' applied to an object of class "lm"

If I however use
apa_lm <- apa_print.lm(lm_out)
It gives no error message. So I've found a workaround but I wanted to report the issue in case someone else has the same problem.

**To Reproduce**
A [minimal complete verifiable example](https://stackoverflow.com/help/mcve) and the error message if applicable.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by mariusbarth** [comment] 2020-05-29 11:36
Hi! This is a known problem with S3 method dispatch. The problem should be fixed if you install from the development branch:
```
remotes::install_github("crsh/papaja@devel")
```
Would be great to hear from you if this solved your problem.

**Comment by crsh** [comment] 2020-05-29 11:58
Duplicate of #361

**Comment by henda52** [comment] 2020-06-03 08:45
I get strange error messages when I try to install the development branch version of papaja and I cannot get it to be installed properly. So I cannot check if it works with that version, but since I have the workaround it is not a problem for me anymore.
Tanks for the help!

**Comment by crsh** [comment] 2020-06-03 10:33
Hi Henrik, would you mind sharing the error message with us? Maybe we can do something to fix it.

**Comment by henda52** [comment] 2020-06-03 13:16
Just because you asked, there were no error messages this time and it got installed. Strange!

However, now I can answer your first question. When I write:
apa_lm <- apa_print(lm_out)
It works! However, when I write:
apa_lm <- papaja::apa_print.lm(lm_out)
I get this error message:
Error: 'apa_print.lm' is not an exported object from 'namespace:papaja'

So I got the opposite from before, now apa_print works but not apa_print.lm.

**Comment by mariusbarth** [comment] 2020-06-06 17:00
Hi Henrik, thanks for reporting back!

The behavior you describe (after updating) is indeed what I was striving for when I implemented the bug fix. I know this might be a bit surprising, especially because some `papaja` users tend to call S3 methods directly by using `apa_print.lm()`, `apa_print.htest()`, etc. Let me first explain why the current behavior occurs, why we opted for this solution, and how you might still work around it if you need to.

The reason for the behavior is that while the generic function `apa_print()` is exported, its S3 methods `apa_print.htest()`, `apa_print.lm()` are _registered_, but not _exported_. As a result,  applying `apa_print()` to any supported object should always yield the correct result, while trying to directly call specific methods (e.g., via `apa_print.lm()`) returns an error.

This is a result of the fact that we use the `roxygen2`package to generate our `NAMESPACE` file, and the roxygen2 package authors consider **not** to export individual methods the only correct behavior ([see here](https://github.com/r-lib/roxygen2/issues/805])). This is inconsistent with what users know from packages like `stats`, where some S3 methods like `aggregate.data.frame()` are exported alongside the generic function `aggregate()`; however, this only seems to be motivated by maintaining backwards compatibility.

We decided not to work around the behavior of `roxygen2`: it would most likely be a messy and error-prone hack, and moreover,  the overall maintainability of `papaja` would suffer from exporting all methods. Moreover, now that the method dispatch is fixed, it should do its job again -- that is, selecting S3 methods based on the class of the object that is handed to the generic function.

If you really want to bypass the method dispatch, you can still call methods directly by writing
`papaja:::apa_print.lm()` (with three `:::`), but I don't recommend that because it may or may not be supported in future releases of `papaja`.

I am keepink this issue open, because I think we should mention this in the documentation somewhere.

**Comment by henda52** [comment] 2020-06-08 06:28
Thank you for the detailed feedback! I now know how to use apa_print properly and it work. Thanks again!

**Comment by mariusbarth** [comment] 2020-07-20 13:18
Hi @henda52, we merged the changes that addressed your problem onto the `master` branch and it should thus be resolved. Before I close this issue, can you confirm that the method dispatch properly works after installing the newest release from the master branch via `remotes::install_github("crsh/papaja")`?

**Closed** 2022-03-17 16:32 UTC
Labels: bug, documentation
