### ISSUE TITLE
Error: `x` and `labels` must be same type Execution halted

### ISSUE THREAD

**Issue by brynhughes** [crsh/papaja#224] opened 2018-06-29 17:25 UTC
Hi!

When trying to knit a document, I am getting this error:

Error: `x` and `labels` must be same type Execution halted

I don't get the error when running the code as an R script, or as a code chunk within my Rmd file. Only when knitting the entire document. I suspect it has something to do with apa_print, but I'm not entirely sure. Hopefully, someone here can help me out.

I've attached my .Rmd file for reference. 

[backbeatPlacement.txt](https://github.com/crsh/papaja/files/2150280/backbeatPlacement.txt)

**Comment by mariusbarth** [comment] 2018-07-02 09:07
Hi @brynhughes,
this is a known issue that was solved on the development branch, but is not yet available on the master branch. To install from the development branch, use `devtools::install_github("crsh/papaja@devel")`.
Hope this also does the trick for you.

**Comment by crsh** [comment] 2018-07-05 08:08
Duplicate of https://github.com/crsh/papaja/issues/199

**Closed by crsh** 2018-07-05 08:08 UTC
