### ISSUE TITLE
Error running filter ampersand_filter.sh

### ISSUE THREAD

**Issue by mshibl** [crsh/papaja#135] opened 2017-07-29 18:28 UTC
I'm new to R Studio in general, and I started using papaja as a requirement for my school course.
When I try to knit I get the following error:
![error](https://monosnap.com/file/pl4f2mGozZZFSjHEj99xhQSPSfMukK.png)

This error goes away if I add the following config: `citeproc: no` however if I do that the citations are not extracted and inserted to the last page!

Please let me know if you need more information?

Thank you,

**Comment by crsh** [comment] 2017-08-01 08:41
Hi Mohamed, could you provide me with a reproducible example of the problem, i.e. the .Rmd and the .bib file?

**Comment by crsh** [comment] 2017-11-06 10:58
I'm closing this issue for now because I cannot reproduce it.

**Closed by crsh** 2017-11-06 10:58 UTC
