### ISSUE TITLE
Adding table note results in ! Misplaced \noalign error.

### ISSUE THREAD

**Issue by HanZhang-psych** [crsh/papaja#450] opened 2021-04-19 17:08 UTC
**Describe the bug**
I'm trying to reproduce the examples provided under the apa_table() function but noticed that knitr gives me a  Misplaced \noalign error when I include a `note=` argument

**To Reproduce**
```
my_table <- t(apply(cars, 2, function(x) # Create data
  round(c(Mean = mean(x), SD = sd(x), Min = min(x), Max = max(x)), 2)
))

apa_table(
  my_table
  , align = c("l", rep("r", 3))
  , caption = "A summary table of the cars dataset."
  , note = 'something.' # add this will give me an error
)
```
If I go to the .tex file and manually delete the `\addlinespace` line the output is generated correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/17090544/115275395-be0c7180-a10f-11eb-97c3-a805662cc4e5.png)

**Additional context**

I'm using the dev version of papaja but noticed that the problem also occurs for the stable version.

```
> sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] papaja_0.1.0.9997 rstudioapi_0.13   knitr_1.32        magrittr_2.0.1    usethis_2.0.1    
 [6] devtools_2.4.0    pkgload_1.2.1     R6_2.5.0          rlang_0.4.10      fastmap_1.1.0    
[11] tools_4.0.5       pkgbuild_1.2.0    xfun_0.22         sessioninfo_1.1.1 cli_2.4.0        
[16] withr_2.4.2       htmltools_0.5.1.1 ellipsis_0.3.1    remotes_2.3.0     yaml_2.2.1       
[21] digest_0.6.27     rprojroot_2.0.2   lifecycle_1.0.0   crayon_1.4.1      processx_3.5.1   
[26] purrr_0.3.4       callr_3.6.0       vctrs_0.3.7       fs_1.5.0          ps_1.6.0         
[31] curl_4.3          testthat_3.0.2    memoise_2.0.0     glue_1.4.2        cachem_1.0.4     
[36] evaluate_0.14     rmarkdown_2.7     compiler_4.0.5    tinylabels_0.2.1  desc_1.3.0       
[41] prettyunits_1.1.1
```

Thank you,
Han

**Comment by mariusbarth** [comment] 2021-04-19 17:36
I cannot reproduce the error message on a Windows machine. Can you provide a (minimal) `test.tex` that causes the problem?

**Comment by HanZhang-psych** [comment] 2021-04-19 17:46
Sure. I've included both the .rmd and the .tex file in the zip folder. The problematic `\addlinespace` code is at line 228

[test.zip](https://github.com/crsh/papaja/files/6338028/test.zip)

**Comment by mariusbarth** [comment] 2021-04-19 19:10
I think I found the reason for this problem: A recent update in `knitr::kable()` adds some additional `{}` after `\toprule`, `\midrule`, and `\bottomrule`, which seems to break LaTeX processing not only for **papaja** but also for **kableExtra**: https://github.com/yihui/tinytex/runs/2383210231.

**Comment by mariusbarth** [comment] 2021-04-19 19:12
Related to https://github.com/yihui/knitr/issues/1595

**Comment by HanZhang-psych** [comment] 2021-04-19 19:29
Can confirm it's working after adding the options. Thanks!

**Comment by mariusbarth** [comment] 2021-04-21 12:31
It seems like the problem has already been fixed in the development version of **knitr**. You can install via
```
remotes::install_github('yihui/knitr')
```
Would be great to hear back from you if this also solves the problem without using the workaround

**Comment by HanZhang-psych** [comment] 2021-04-26 13:50
Sorry for the delay. Can confirm the issue is solved by installing the latest development version of knitr without using the workaround.

**Comment by mariusbarth** [comment] 2021-04-26 13:52
Great, thanks for your feedback!

**Closed by mariusbarth** 2021-04-26 13:52 UTC
Labels: bug
