### ISSUE TITLE
Table not generated in TeX correctly when label contains "_"

### ISSUE THREAD

**Issue by weixulu** [crsh/papaja#242] opened 2018-08-23 01:21 UTC
I had this code in my document. It was rendered perfectly without papaja. 

`Table \ref{tab:tab_freq_activities} shows`
~~~
```{r tab_freq_activities, echo=FALSE}
library(kableExtra)
dt <- read.csv(file = "tab_freq_activities.csv", header = T)
knitr::kable(
  dt, booktabs = TRUE,
  caption = 'Frequencies of mentions of various activities by the participants',
  col.names=c(" ", "Frequency of mentions", "Number of participants")
)
```
~~~
However, when I render it to PDF with papaja, it generated TeX codes like this (with the unnecessary \textbackslash{}): 

```
Table \ref{tab:tab_freq_activities} shows \textbackslash{}begin\{table\}

\textbackslash{}caption\{(\#tab:tab\_freq\_activities)Frequencies of
mentions of various activities by the participants\} \centering

\begin{tabular}[t]{lrr}
\toprule
  & Frequency of mentions & Number of participants\\
\midrule
Cultural activities & 7 & 5\\
Shopping & 7 & 7\\
Outdoor sports & 6 & 5\\
Sightseeing & 3 & 3\\
Food and drinks & 59 & 27\\
All others & 21 & 22\\
\bottomrule
\end{tabular}

\textbackslash{}end\{table\}  
```

Then, I don't know why I did it, but I changed to label id to "tabFreqActivities" (simply removing the "_"), it was generated correctly like this:

```
Table \ref{tab:tabFreqActivities} shows

\begin{table}

\caption{\label{tab:tabFreqActivities}Frequencies of mentions of various activities by the participants}
\centering
\begin{tabular}[t]{lrr}
\toprule
  & Frequency of mentions & Number of participants\\
\midrule
Cultural activities & 7 & 5\\
Shopping & 7 & 7\\
Outdoor sports & 6 & 5\\
Sightseeing & 3 & 3\\
Food and drinks & 59 & 27\\
All others & 21 & 22\\
\bottomrule
\end{tabular}
\end{table}
```

Other Info:
```
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] papaja_0.1.0.9842 kableExtra_0.9.0 

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18      rstudioapi_0.7    knitr_1.20       
 [4] xml2_1.2.0        magrittr_1.5      hms_0.4.2        
 [7] munsell_0.5.0     rvest_0.3.2       viridisLite_0.3.0
[10] colorspace_1.3-2  R6_2.2.2          rlang_0.2.1      
[13] highr_0.7         stringr_1.3.1     httr_1.3.1       
[16] tools_3.5.1       htmltools_0.3.6   yaml_2.2.0       
[19] rprojroot_1.3-2   digest_0.6.15     tibble_1.4.2     
[22] crayon_1.3.4      readr_1.1.1       evaluate_0.11    
[25] rmarkdown_1.10    stringi_1.1.7     compiler_3.5.1   
[28] pillar_1.3.0      scales_1.0.0      backports_1.1.2  
[31] pkgconfig_2.0.1  ```

**Comment by crsh** [comment] 2018-08-23 08:28
Hi, thanks for the question. I just tried this by adding this chunk to a new `papaja` document:

~~~r
```{r tab_freq_activities, echo=FALSE}
knitr::kable(
  cars[1:5, ], booktabs = TRUE,
  caption = 'Frequencies of mentions of various activities by the participants',
  col.names=c("Frequency of mentions", "Number of participants")
)
```
~~~

I'm getting this LaTeX error

~~~
! Missing $ inserted.
<inserted text> 
                $
l.175 ...f various activities by the participants}
~~~

This is, however, not a `papaja` specific issue but is due to the use of `bookdown::pdf_document2()`. You  can see that by the YAML front matter:

~~~yaml
# documentclass     : "apa6"
classoption       : "man"
output            : bookdown::pdf_document2
~~~

This will give you the same error, whereas it works with `rmarkdown::pdf_document()`:

~~~yaml
# documentclass     : "apa6"
classoption       : "man"
output            : pdf_document
~~~

The reason is, I think, that `bookdown` uses the chunk names to generate cross-references: https://bookdown.org/yihui/bookdown/figures.html

I'm not sure it's intended behavior that the chunk names are used verbatim here, which causes this error. At any rate, this is an issue that needs to be raised at the `bookdown` repository. Hence, I'll close this issue. If I'm missing something, feel free to reopen.

**Closed by crsh** 2018-08-23 08:28 UTC
Labels: question
