### ISSUE TITLE
APA template generates duplicate references in reference list (reopened) 

### ISSUE THREAD

**Issue by cityofsmiles87** [crsh/papaja#338] opened 2019-12-27 18:48 UTC
Hi. Since this issue was already described [here](https://github.com/crsh/papaja/issues/121) but no further info was offered by [dragfindel](https://github.com/dragfindel), I decided to reopen it. I was able to install the latest development snapshot of papaja in Fedora and Ubuntu and tried to render the template as described in [the papaja intro](https://crsh.github.io/papaja_man/introduction.html#creating-a-document) for the R command line. The default manuscript was rendered without error, however the r-references were produced in duplicate. I thought that it was just a hardware issue since the Fedora and Ubuntu OSes were installed inside the [Termux](https://termux.com/) app. Therefore, I installed Pandoc, Texlive-full, and the RStudio Server in LinuxLite OS running in my Lenovo laptop. When I knitted the template provided by papaja, the references were also produced in duplicate. I'm totally at a loss now. Is there anything that I missed? I have read the [software requirements ](https://crsh.github.io/papaja_man/introduction.html#software-requirements) and the manuscripts were rendered without errors.  Any ideas?

**Comment by cityofsmiles87** [comment] 2019-12-28 00:03
Here's my session info. 

R version 3.6.1 (2019-07-05)
Platform: aarch64-redhat-linux-gnu (64-bit)
Running under: Fedora 31 (Container Image)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] papaja_0.1.0.9842

loaded via a namespace (and not attached):
 [1] compiler_3.6.1  magrittr_1.5    bookdown_0.16   htmltools_0.4.0
 [5] tools_3.6.1     yaml_2.2.0      tinytex_0.18    Rcpp_1.0.3
 [9] stringi_1.4.3   rmarkdown_2.0   knitr_1.26      stringr_1.4.0
[13] digest_0.6.23   xfun_0.11       rlang_0.4.2     evaluate_0.14

**Comment by cityofsmiles87** [comment] 2019-12-28 00:05
Here's what the references output looks like. 

 ![Screenshot_20191228-080312](https://user-images.githubusercontent.com/52723831/71536320-b63c2300-2948-11ea-9f5e-d42de507b9c6.jpg)

**Comment by cityofsmiles87** [comment] 2019-12-28 00:07
Only one warning message was produced. I hope this helps. 

Warning message:
LaTeX Warning: Command \@parboxrestore  has changed.
               Check if current package is valid.

**Comment by cityofsmiles87** [comment] 2019-12-28 00:12
Here's the whole output from the R command line. 

> rmarkdown::render("mymanuscript.Rmd")


processing file: mymanuscript.Rmd
  |                                                 |                                                 |                                                 |..........                                                            |  14%
  ordinary text without R code

  |                                                 |....................                                                  |  29%
label: setup (with options)
List of 1
 $ include: logi FALSE

  |                                                 |..............................                                        |  43%
  ordinary text without R code

  |                                                 |........................................                              |  57%
label: analysis-preferences
  |                                                 |..................................................                    |  71%
   inline R code fragments

  |                                                 |............................................................          |  86%
label: create_r-references
  |                                                 |......................................................................| 100%
  ordinary text without R code


output file: mymanuscript.knit.md

/bin/pandoc +RTS -K512m -RTS mymanuscript.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash+raw_attribute --output mymanuscript.tex --self-contained --highlight-style tango --pdf-engine pdflatex --variable graphics --lua-filter /usr/lib64/R/library/rmarkdown/rmd/lua/pagebreak.lua --lua-filter /usr/lib64/R/library/rmarkdown/rmd/lua/latex-div.lua --wrap preserve --csl /usr/lib64/R/library/papaja/rmd/apa6.csl --filter /bin/pandoc-citeproc --filter /usr/lib64/R/library/papaja/rmd/ampersand_filter.R --filter /bin/pandoc-citeproc

Output created: mymanuscript.pdf
Warning message:
LaTeX Warning: Command \@parboxrestore  has changed.
               Check if current package is valid.

**Comment by ericpgreen** [comment] 2019-12-30 18:03
I'm seeing the same duplication with my own use case.

```
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14.5

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.3.2

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3        papaja_0.1.0.9842 rstudioapi_0.10   knitr_1.26        xml2_1.2.0       
 [6] magrittr_1.5      xtable_1.8-4      R6_2.4.1          rlang_0.4.2       bibtex_0.4.2     
[11] plyr_1.8.4        stringr_1.4.0     httr_1.4.0        tools_3.5.0       packrat_0.4.9-3  
[16] xfun_0.11         miniUI_0.1.1.1    htmltools_0.4.0   shinyjs_1.0       yaml_2.2.0       
[21] assertthat_0.2.1  digest_0.6.23     RefManageR_1.2.0  later_0.8.0       promises_1.0.1   
[26] curl_3.3          evaluate_0.14     mime_0.7          rmarkdown_2.0     stringi_1.4.3    
[31] compiler_3.5.0    citr_0.3.2        jsonlite_1.6      lubridate_1.7.4   httpuv_1.5.1  
```

**Comment by cityofsmiles87** [comment] 2020-01-02 12:01
Do you think this is a bug, @ericpgreen? What fixes have you tried?

**Comment by ericpgreen** [comment] 2020-01-03 01:42
I'm not sure. Maybe a change in pandoc, knitr, or rmarkdown?

**Comment by rlucas11** [comment] 2020-01-04 20:44
This also just started happening for me. It's a document that I just returned to after not having worked on it for a couple weeks, but I didn't look closely at the reference section the last time I worked on it, so I'm not sure how long it has been this way (I just noticed it). Happy to provide more detail, but not sure what else to try.

```> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux```

**Comment by cityofsmiles87** [comment] 2020-01-05 14:36
Oddly, I feel relieved now because I thought I was the only one experiencing this.

**Comment by rlucas11** [comment] 2020-01-06 17:44
I just tried it the same doc on my work computer and I do not get the duplicate references. I think the only difference across computers is that I had not yet updated rmarkdown from 1.18 to 2.0. I now have to check on my other computer, but I'm pretty sure that papaja (0.1.0.9842) and knitr (1.26) are the same, and I usually keep pandoc updated to the latest version on both computers, so it should be the same, too. So maybe it's due to a change in rmarkdown package?

**Comment by cityofsmiles87** [comment] 2020-01-07 16:50
Yes, you're right @rlucas11. I just downgraded rmarkdown to 1.18 and the duplication is gone. Thank you so much for your suggestion.

**Comment by cityofsmiles87** [comment] 2020-01-07 16:51
I'm closing this issue now.

**Comment by ericpgreen** [comment] 2020-01-07 20:30
Rolling back fixes the problem, but I imagine @crsh might want to keep this open for folks who want to patch `papaja` to work with the newer version of `rmarkdown`.

**Comment by cityofsmiles87** [comment] 2020-01-08 14:53
You're right, @ericpgreen. I better leave this open and let @crsh close it if he wants to.

**Comment by rlucas11** [comment] 2020-01-09 11:38
Just another note: I don't know if this is related, but I just noticed that for me, the ampersand filter did not work with rmarkdown 2.0. Downgrading to 1.18 also fixed the ampersand filter issue.

**Comment by crsh** [comment] 2020-01-09 14:07
Hi everyone, thanks for narrowing down the problem and sorry for the late response. I'll try to look into this more closely as soon as I can (definitely before next Thursday). Just a quick question: Do you get this behavior even if you remove the following lines from the template?

~~~
<div id = "refs"></div>
~~~

**Comment by ericpgreen** [comment] 2020-01-09 14:25
Thanks! Yes, still happens for me.

**Comment by jrennstich** [comment] 2020-01-10 07:47
> Thanks! Yes, still happens for me.

Same here.

**Comment by cityofsmiles87** [comment] 2020-01-10 17:54
@rlucas11, in my case replace_ampersands: yes did not work even after downgrading rmarkdown to 1.18

**Comment by cityofsmiles87** [comment] 2020-01-10 18:06
@crsh, I just updated rmarkdown to 2.0 and deleted <div id = "refs"></div> from the main Rmd file. The references are still duplicated and the hanging indentation is disabled.

**Comment by cityofsmiles87** [comment] 2020-01-10 18:14
> Just another note: I don't know if this is related, but I just noticed that for me, the ampersand filter did not work with rmarkdown 2.0. Downgrading to 1.18 also fixed the ampersand filter issue.

@rlucas11, in my case `replace_ampersands: yes` did not work even after downgrading rmarkdown to 1.18.

**Comment by CrumpLab** [comment] 2020-01-14 22:38
Seeing this too...was wondering why my reference list was so long.

**Comment by crsh** [comment] 2020-01-15 21:50
Thanks everyone for reporting the problem. This was caused by a change in `rmarkdown` that tripped up a messy hack I'm using to ensure that `pandoc-citeproc` is run before the ampersand filter and word counting. This is bound to break again in the future, so I will need to see if this can be addressed more robustly. But it should work for now.

**Comment by ericpgreen** [comment] 2020-01-15 22:02
@crsh do you mean downgrading rmarkdown as the temp fix?

**Comment by crsh** [comment] 2020-01-15 22:05
Sorry, what I mean is, that I've committed a fix that should ensure compatibility with `rmarkdown` 2.0---in fact, `papaja` now requires it (see DESCRIPTION).

**Comment by ericpgreen** [comment] 2020-01-15 22:06
OK, great! I wasn't seeing the commit, but I'll look again.

**Comment by crsh** [comment] 2020-01-15 22:15
It's https://github.com/crsh/papaja/commit/27f40916c434f83c6a744708816f46fd1461d040 (I'm not proud of it :grimacing:)

**Comment by ericpgreen** [comment] 2020-01-16 10:24
Maybe a silly question here, but this commit is in the development branch, right? I don't see any change if I reinstall with `devtools::install_github("crsh/papaja")`, and reinstalling from `devtools::install_github("crsh/papaja@devel")` gives me an error when compiling. Maybe this is a localized issue for me.

```
! Undefined control sequence.
\@svsechd ...ize \bfseries \itshape \typesectitle 
                                                  {\hskip \parindent \relax ...
```

**Comment by crsh** [comment] 2020-01-16 12:01
Thanks for getting back to me on this so quickly. I've seen this before on my other computer but can't reproduce it here. This is related to a [fix for 4th and 5th level headings](https://github.com/crsh/papaja/commit/153871d6671cafc831e766e46ab420735eff6af4) (if you remove those lines from the TeX-file you should be able to compile it). The problem is the `\typesectitle`, which is [defined](http://ctan.epst-tlemcen.dz/tex-archive/macros/latex/contrib/apa6/apa6.dtx) in the `apa6` document class, at least in the current version. What version of the document class are you using?

At any rate it appears that my fix is sensitive to the setup of the LaTeX distribution, which is clearly not desirable. I've found another way to address this and will push a fix some time later today.

In the meantime, can you confirm that the reference section in the TeX file is not duplicated?

**Comment by ericpgreen** [comment] 2020-01-16 12:17
Thanks @crsh. The TeX file is not duplicated, and removing those lines does allow me to compile the TeX file. Thanks for that.

I think I have Tex Live 2016, so maybe an old version of `apa6`.  I tried to find a version number and came across `\ProvidesClass{apa6}[2014/11/20 v2.14 APA formatting (6th edition)]`.

**Comment by crsh** [comment] 2020-01-16 13:37
Okay, there promised fix has [arrived](https://github.com/crsh/papaja/commit/625dee676672bc2ea51dc357e672ab189cda09fa). When it's convenient for you, let me know if that resolves the problem for you, if the references look right, and if level 4 and 5 headings still look good.

Again thanks for your help and timely feedback!

**Comment by ericpgreen** [comment] 2020-01-16 14:11
Awesome! Thanks for the quick fix. All looks good using the development version.

**Comment by crsh** [comment] 2020-01-16 14:21
:+1:

**Closed** 2020-01-16 23:49 UTC
Labels: bug

**Comment by cityofsmiles87** [comment] 2020-01-17 17:35
It worked! The duplication is gone. Thank you so much @crsh.

**Comment by ktw5691** [comment] 2020-01-18 19:11
I can confirm that, having experience a similar problem of duplicated references, updating to the @devel branch yesterday resolved the problem. Thanks for the fix @crsh.

**Comment by jrennstich** [comment] 2020-01-22 18:06
Thanks for the quick fix!
