### ISSUE TITLE
in text figures with `fig.show = "hold"`

### ISSUE THREAD

**Issue by DJAnderson07** [crsh/papaja#148] opened 2017-09-06 15:56 UTC
Below, I've taken the basic template and added two figures, using fig.show = "hold" as the option. I'm expecting that the output should include both figures on one page, and that seems to work, but unfortunately it also seems that the figs are being displayed in-text, rather than at the end of the document. Following the code I've attached my sessionInfo(). Any help you could provide would be appreciated.

    ---
    title             : "The title"
    shorttitle        : "Title"

    author: 
      - name          : "First Author"
        affiliation   : "1"
        corresponding : yes    # Define only one corresponding author
        address       : "Postal address"
        email         : "my@email.com"
      - name          : "Ernst-August Doelle"
        affiliation   : "1,2"

    affiliation:
      - id            : "1"
        institution   : "Wilhelm-Wundt-University"
      - id            : "2"
        institution   : "Konstanz Business School"

    author_note: |
      Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

      Enter author note here.

    abstract: |
      Enter abstract here. Each new line herein must be indented, like this line.
  
    keywords          : "keywords"
    wordcount         : "X"

    bibliography      : ["r-references.bib"]

    figsintext        : no
    figurelist        : no
    tablelist         : no
    footnotelist      : no
    lineno            : yes

    lang              : "english"
    class             : "man"
    output            : papaja::apa6_pdf
    ---

    ```{r load_packages, include = FALSE}
    library("papaja")
    ```

    Here's an example of a figure showing up in text, instead of as its own separate page, when using `fig.show = "hold"`.

    ```{r, in_text_figs, fig.width = 6.5, fig.height = 4.5, fig.show = "hold"}
    plot(1:5)
    plot(1:10)
    ```

    We used `r cite_r("r-references.bib")` for all our analyses.
    \newpage

    # References
    ```{r create_r-references}
    r_refs(file = "r-references.bib")
    ```

    \setlength{\parindent}{-0.5in}
    \setlength{\leftskip}{0.5in}

---

# sessionInfo()
    R version 3.4.1 (2017-06-30)
    Platform: x86_64-apple-darwin15.6.0 (64-bit)
    Running under: macOS Sierra 10.12.6

    Matrix products: default
    BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
    LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

    locale:
    [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    other attached packages:
    [1] papaja_0.1.0.9492

    loaded via a namespace (and not attached):
     [1] compiler_3.4.1      backports_1.1.0     magrittr_1.5        rprojroot_1.2      
     [5] htmltools_0.3.6     tools_3.4.1         yaml_2.1.14         Rcpp_0.12.12       
     [9] stringi_1.1.5       rmarkdown_1.6       knitr_1.17          stringr_1.2.0      
    [13] digest_0.6.12       autoinst_0.0.0.9000 evaluate_0.10.1

**Comment by crsh** [comment] 2017-09-06 17:01
Hi Daniel, thanks for this. I tried reproducing this with two identical plots earlier (`plot(1:10)`). In that scenario the second plot wasn't displayed at all, which was interesting by itself.

The issue here is that there is no figure environment in the resulting TeX document. The TeX code is

```{tex}
\includegraphics{test_files/figure-latex/unnamed-chunk-1-1.pdf}
\includegraphics{test_files/figure-latex/unnamed-chunk-1-2.pdf}
```
instead of

```{tex}
\begin{figure}
\centering
\includegraphics{encoding_files/figure-latex/unnamed-chunk-1-1.pdf}
\includegraphics{test_files/figure-latex/unnamed-chunk-1-2.pdf}
\caption{}
\end{figure}
```

Note, that the `fig.cap` is also ignored. I played around with this some more and it seems this is a more general `knitr` related issue. The same problem occurs when creating a regular PDF with `rmarkdown::pdf_document()`. `fig.show = "hold"` only makes sense if `echo = TRUE`. In `papaja` `echo = FALSE` is the default for all chunks. If you manually set `echo = TRUE` for the chunk that generates the plots it should work as expected. I agree that this behavior is confusing but there's nothing I can do about it from the `papaja` side of things. I think it may be worth reporting this issue at either the `knitr` or the  `rmarkdown` repository, though.

That said, I wonder what your usecase is. Generally, I would recommend creating separate chunks for each figure because otherwise you will end up with figures that have identical captions, which is rarely desirable.

**Comment by DJAnderson07** [comment] 2017-09-06 17:10
Thanks Fredrick,

The issue is that I’m trying to basically display two contrasting visualizations of the same thing in a single figure, so the reader can see two different representations and see how they are similar and how they are different. I potentially could us `par(mfrow = c(2, 1))` but that is somewhat less than ideal and not the method Yihui recommends (see, for example, here https://tex.stackexchange.com/questions/117828/plot-two-figures-side-by-side-in-knitr-without-changing-mfrow <https://tex.stackexchange.com/questions/117828/plot-two-figures-side-by-side-in-knitr-without-changing-mfrow>).

Anyway, I appreciate you looking into this. I will figure out a workaround.

Thanks,
--
Daniel Anderson
IES Post-Doctoral Research Fellow
Center on Teaching and Learning
University of Oregon

**Comment by crsh** [comment] 2017-09-07 08:46
I see. When I used `fig.show = "hold"` and `echo = TRUE` I got two separate figure environments using both `papaja::apa_pdf()` and `rmarkdown::pdf_document()`. Not really what you are looking for.

You could also use [subfigures](https://stackoverflow.com/questions/12546365/subfigures-or-subcaptions-with-knitr), but I usually just partition my device (e.g. with `mfrow()`). My reading of the SE thread is that OP asked specifically for a solution other than `mfrow()`; I don't think Yihui would advise against the use of `mfrow()` and the like.

I'll close the issue for now because it doesn't seem to be related to `papaja. If you find a solution to this, let me know.

**Closed by crsh** 2017-09-07 08:46 UTC
Labels: question

**Comment by DJAnderson07** [comment] 2017-09-07 14:00
Okay, thanks. And yes, looks like I may have been misremembering recommendations about `par()` (that link I sent was just the first one I found, I thought there were explicit mentions in the book but I didn’t find any with a  quick glance through). Anyway, thanks again.

Thanks,
--
Daniel Anderson
IES Post-Doctoral Research Fellow
Center on Teaching and Learning
University of Oregon

**Comment by cjvanlissa** [comment] 2020-05-21 12:56
I have the same problem that a figure is shown in text, and the latex version of the document has no figure environment. My figure chunk is:

```
```{r, scholarbib, echo = FALSE}
knitr::include_graphics("scholar_bib.png")
```
```

The resulting TeX file says:

`

\includegraphics{scholar_bib.png}

`

Any idea why?

**Comment by crsh** [comment] 2020-05-21 15:16
Have you tried adding a figure caption?

Sent from my phone
