### ISSUE TITLE
Incorrect estimate label in `apa_print()` for `emmeans` interaction contrast

### ISSUE THREAD

**Issue by shirdekel** [crsh/papaja#456] opened 2021-06-07 00:52 UTC
**Describe the bug**
`apa_print()` uses (what seems like to me to be) an incorrect estimate label for `emmeans` interaction contrasts.

**To Reproduce**
``` r
library(papaja)
#> Loading required package: tinylabels
library(emmeans)

model <- lm(mpg ~ vs * am, data = mtcars)

emm <- emmeans(model, ~ vs * am)

emm_contrast_1 <- contrast(emm, "pairwise")

apa_print(emm_contrast_1)
#> $estimate
#> $estimate$`00_10`
#> [1] "$\\Delta M = -5.69$, 95\\% CI $[-10.20,~-1.18]$"
#> 
#> $estimate$`00_01`
#> [1] "$\\Delta M = -4.70$, 95\\% CI $[-9.44,~0.04]$"
#> 
#> $estimate$`00_11`
#> [1] "$\\Delta M = -13.32$, 95\\% CI $[-17.83,~-8.81]$"
#> 
#> $estimate$`10_01`
#> [1] "$\\Delta M = 0.99$, 95\\% CI $[-4.28,~6.27]$"
#> 
#> $estimate$`10_11`
#> [1] "$\\Delta M = -7.63$, 95\\% CI $[-12.70,~-2.56]$"
#> 
#> $estimate$`01_11`
#> [1] "$\\Delta M = -8.62$, 95\\% CI $[-13.89,~-3.35]$"
#> 
#> 
#> $statistic
#> $statistic$`00_10`
#> [1] "$t(28) = -3.45$, $p = .009$"
#> 
#> $statistic$`00_01`
#> [1] "$t(28) = -2.71$, $p = .053$"
#> 
#> $statistic$`00_11`
#> [1] "$t(28) = -8.07$, $p < .001$"
#> 
#> $statistic$`10_01`
#> [1] "$t(28) = 0.51$, $p = .955$"
#> 
#> $statistic$`10_11`
#> [1] "$t(28) = -4.11$, $p = .002$"
#> 
#> $statistic$`01_11`
#> [1] "$t(28) = -4.46$, $p = .001$"
#> 
#> 
#> $full_result
#> $full_result$`00_10`
#> [1] "$\\Delta M = -5.69$, 95\\% CI $[-10.20,~-1.18]$, $t(28) = -3.45$, $p = .009$"
#> 
#> $full_result$`00_01`
#> [1] "$\\Delta M = -4.70$, 95\\% CI $[-9.44,~0.04]$, $t(28) = -2.71$, $p = .053$"
#> 
#> $full_result$`00_11`
#> [1] "$\\Delta M = -13.32$, 95\\% CI $[-17.83,~-8.81]$, $t(28) = -8.07$, $p < .001$"
#> 
#> $full_result$`10_01`
#> [1] "$\\Delta M = 0.99$, 95\\% CI $[-4.28,~6.27]$, $t(28) = 0.51$, $p = .955$"
#> 
#> $full_result$`10_11`
#> [1] "$\\Delta M = -7.63$, 95\\% CI $[-12.70,~-2.56]$, $t(28) = -4.11$, $p = .002$"
#> 
#> $full_result$`01_11`
#> [1] "$\\Delta M = -8.62$, 95\\% CI $[-13.89,~-3.35]$, $t(28) = -4.46$, $p = .001$"
#> 
#> 
#> $table
#> A data.frame with 5 labelled columns:
#> 
#>        contrast estimate        conf.int statistic p.value
#> 00_10 0 0 - 1 0    -5.69 [-10.20, -1.18]     -3.45    .009
#> 00_01 0 0 - 0 1    -4.70   [-9.44, 0.04]     -2.71    .053
#> 00_11 0 0 - 1 1   -13.32 [-17.83, -8.81]     -8.07  < .001
#> 10_01 1 0 - 0 1     0.99   [-4.28, 6.27]      0.51    .955
#> 10_11 1 0 - 1 1    -7.63 [-12.70, -2.56]     -4.11    .002
#> 01_11 0 1 - 1 1    -8.62 [-13.89, -3.35]     -4.46    .001
#> 
#> contrast : Contrast 
#> estimate : $\\Delta M$ 
#> conf.int : 95\\% CI 
#> statistic: $t(28)$ 
#> p.value  : $p$ 
#> attr(,"class")
#> [1] "apa_results" "list"

emm_contrast_2 <- contrast(emm, interaction = "pairwise")

apa_print(emm_contrast_2)
#> $estimate
#> $estimate$`0_1_0_1`
#> [1] "$M = 2.93$, 95\\% CI $[-2.28,~8.13]$"
#> 
#> 
#> $statistic
#> $statistic$`0_1_0_1`
#> [1] "$t(28) = 1.15$, $p = .259$"
#> 
#> 
#> $full_result
#> $full_result$`0_1_0_1`
#> [1] "$M = 2.93$, 95\\% CI $[-2.28,~8.13]$, $t(28) = 1.15$, $p = .259$"
#> 
#> 
#> $table
#> A data.frame with 6 labelled columns:
#> 
#>         am_pairwise vs_pairwise estimate      conf.int statistic p.value
#> 0_1_0_1       0 - 1       0 - 1     2.93 [-2.28, 8.13]      1.15    .259
#> 
#> am_pairwise: am_pairwise 
#> vs_pairwise: vs_pairwise 
#> estimate   : $M$ 
#> conf.int   : 95\\% CI 
#> statistic  : $t(28)$ 
#> p.value    : $p$ 
#> attr(,"class")
#> [1] "apa_results" "list"
```

<sup>Created on 2021-06-07 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.0.2 (2020-06-22)
#>  os       macOS Mojave 10.14.6        
#>  system   x86_64, darwin17.0          
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_AU.UTF-8                 
#>  ctype    en_AU.UTF-8                 
#>  tz       Australia/Sydney            
#>  date     2021-06-07                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package      * version     date       lib source                            
#>  backports      1.2.1       2020-12-09 [1] CRAN (R 4.0.2)                    
#>  cli            2.5.0       2021-04-26 [1] CRAN (R 4.0.2)                    
#>  coda           0.19-4      2020-09-30 [1] CRAN (R 4.0.2)                    
#>  crayon         1.4.1       2021-02-08 [1] CRAN (R 4.0.2)                    
#>  digest         0.6.27      2020-10-24 [1] CRAN (R 4.0.2)                    
#>  ellipsis       0.3.2       2021-04-29 [1] CRAN (R 4.0.2)                    
#>  emmeans      * 1.5.4-09004 2021-03-11 [1] Github (rvlenth/emmeans@7815617)  
#>  estimability   1.3         2018-02-11 [1] CRAN (R 4.0.0)                    
#>  evaluate       0.14        2019-05-28 [1] CRAN (R 4.0.0)                    
#>  fansi          0.5.0       2021-05-25 [1] CRAN (R 4.0.2)                    
#>  fs             1.5.0       2020-07-31 [1] CRAN (R 4.0.2)                    
#>  glue           1.4.2       2020-08-27 [1] CRAN (R 4.0.2)                    
#>  highr          0.9         2021-04-16 [1] CRAN (R 4.0.2)                    
#>  htmltools      0.5.1.1     2021-01-22 [1] CRAN (R 4.0.2)                    
#>  knitr          1.33        2021-04-24 [1] CRAN (R 4.0.2)                    
#>  lattice        0.20-41     2020-04-02 [1] CRAN (R 4.0.2)                    
#>  lifecycle      1.0.0       2021-02-15 [1] CRAN (R 4.0.2)                    
#>  magrittr       2.0.1       2020-11-17 [1] CRAN (R 4.0.2)                    
#>  mvtnorm        1.1-1       2020-06-09 [1] CRAN (R 4.0.2)                    
#>  papaja       * 0.1.0.9997  2021-06-07 [1] Github (crsh/papaja@c5efb4c)      
#>  pillar         1.6.1       2021-05-16 [1] CRAN (R 4.0.2)                    
#>  pkgconfig      2.0.3       2019-09-22 [1] CRAN (R 4.0.0)                    
#>  plyr           1.8.6       2020-03-03 [1] CRAN (R 4.0.0)                    
#>  purrr          0.3.4       2020-04-17 [1] CRAN (R 4.0.0)                    
#>  Rcpp           1.0.6       2021-01-15 [1] CRAN (R 4.0.2)                    
#>  reprex         1.0.0       2021-01-27 [1] CRAN (R 4.0.2)                    
#>  rlang          0.4.11      2021-04-30 [1] CRAN (R 4.0.2)                    
#>  rmarkdown      2.8.6       2021-06-07 [1] Github (rstudio/rmarkdown@9dc5d97)
#>  sessioninfo    1.1.1       2018-11-05 [1] CRAN (R 4.0.0)                    
#>  stringi        1.6.2       2021-05-17 [1] CRAN (R 4.0.2)                    
#>  stringr        1.4.0       2019-02-10 [1] CRAN (R 4.0.0)                    
#>  styler         1.3.2       2020-02-23 [1] CRAN (R 4.0.0)                    
#>  tibble         3.1.2       2021-05-16 [1] CRAN (R 4.0.2)                    
#>  tinylabels   * 0.2.1       2021-03-27 [1] CRAN (R 4.0.2)                    
#>  utf8           1.2.1       2021-03-12 [1] CRAN (R 4.0.2)                    
#>  vctrs          0.3.8       2021-04-29 [1] CRAN (R 4.0.2)                    
#>  withr          2.4.2       2021-04-18 [1] CRAN (R 4.0.2)                    
#>  xfun           0.23        2021-05-15 [1] CRAN (R 4.0.2)                    
#>  xtable         1.8-4       2019-04-21 [1] CRAN (R 4.0.0)                    
#>  yaml           2.2.1       2020-02-01 [1] CRAN (R 4.0.2)                    
#> 
#> [1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library
```

</details>

**Expected behavior**
That the estimate label would be `$\\Delta M$` for both types of contrasts.

**Additional context**
Seems to be dependent on [`est_name_from_call()`](https://github.com/crsh/papaja/blob/a231c3628ccf24359cc17f11a5bbc743e3fed920/R/apa_print_emm_lsm.R#L316-L345), but I haven't looked more into it.

**Comment by mariusbarth** [comment] 2021-07-08 10:14
Hi @shirdekel,

I can confirm this is a bug that seems to appear with most recent versions of the **emmeans** package. I just pushed a fix to the development branch. You can install via `remotes::install_github("crsh/papaja@devel") and check if it works for you. Please write me back if this solved the bug with your setup, too.

Best,
Marius

**Comment by shirdekel** [comment] 2021-07-18 11:09
Yep, works for me now!

**Comment by mariusbarth** [comment] 2021-07-18 22:21
Perfect, thanks for checking!

**Comment by Misch007** [comment] 2021-08-19 06:44
Hey!

Not sure if this is a bug or the expected behaviour due to my limited statistic knowledge, but when `emmeans` returns an Inf number of degrees for my contrasts and I use `apa_print()`, the label of the variable looks like this: `$t($\\infty$)$`, which results in empty brackets "t()" when I knit it to docx.

Best regards and thanks for the help in advance,
Mischa

**Comment by crsh** [comment] 2021-08-31 15:00
Hi @Misch007, this is indeed a bug, it should be `$t(\\infty)$`. Thanks for pointing this out. I'll look into it.

**Comment by crsh** [comment] 2021-09-01 13:04
I just pushed a commit to a feature branch, which I think should fix the issue. You can give it a try by installing `remotes::install_github("crsh/papaja@emmeans")`. Let me know if it works for you.

**Comment by Misch007** [comment] 2021-09-02 09:39
Hey @crsh,

I am afraid I cannot test it but have to report another bug instead...

The case in which I got the Inf output was, when subsetting the `emmeans(..., type = "response")` function, after I got the contrasts returned on the log scale. With the `@devel` branch it worked fine with `apa_print()` but in your feature branch I am now getting the following error message:

```
Error in printnum.default(tidy_x$estimate, ...) : 
  The parameter 'x' is NULL. Please provide a value for 'x'
```
Here's an exemplary code, for which I am now receiving the error:

```
afex_options(emmeans_model = "multivariate")

participant<-c(1:40)
group<-c("intervention", "control","control","intervention","control")

df<-data.frame(participant,group) %>% 
  group_by(participant,group) %>% 
  summarise(session=c("t1","t2","t3","t4")) %>% 
  group_by(participant, group, session) %>% 
  summarise(task=c("a","b")) %>% 
  ungroup() %>% 
  mutate(errors=floor(runif(n=320,min=0,max=30)))

glmm <- mixed(errors~group*session*task+(1|participant), df, family='poisson', method='LRT')

contr<-emmeans(glmm, pairwise~session, type="response")

apa_print(contr$contrasts)
```

Maybe the following is therefore of interest to you.... Also in the `@devel` branch there is a bug I found with the  `emmeans(..., type = "response")` function, but I was not sure if it is relevant being very specific, so I didn't report it yet. When using the `apa_print()` call on an `emmeans(..., type = "response")` output, when the data was NOT on the log scale and actually the `type = "response"` subset is not necessary, I am getting the following error message:
```
glmm <- mixed(errors~group*session*task+(1|participant), df)

contr<-emmeans(glmm, pairwise~session, type="response")

apa_print(contr$contrasts)

Error in if (x@misc$inv.lbl == "ratio" && !is.null(x@misc$predict.type) &&  : 
  missing value where TRUE/FALSE needed
```
Sorry for filling your to-do list with stuff I am not sure if it is actually necessary...
Mischa

**Comment by crsh** [comment] 2021-09-02 10:09
Hi Mischa, thanks again for your reporting. I cannot reproduce these errors using the PR-branch. Did you install using `remotes::install_github("crsh/papaja@emmeans")`?

**Comment by Misch007** [comment] 2021-09-02 10:26
Hey @crsh,

sorry for the confusion!

So with the `remotes::install_github("crsh/papaja@devel")` branch I am not having any errors when the output of `emmeans()` is on the log scale and the `type = "response"` subset is actually transforming them back, this works perfectly fine except for the wrong estimate lable `$t($\\infty$)$`, see example:

```
glmm <- mixed(errors~group*session*task+(1|participant), df, family='poisson', method='LRT')

contr<-emmeans(glmm, pairwise~session, type="response")

apa_print(contr$contrasts) 

$estimate
$estimate$t1_t2
[1] "$Ratio = 0.97$, 95\\% CI $[0.87,~1.08]$"

$estimate$t1_t3
[1] "$Ratio = 0.93$, 95\\% CI $[0.83,~1.03]$"

$estimate$t1_t4
[1] "$Ratio = 0.85$, 95\\% CI $[0.76,~0.94]$"

$estimate$t2_t3
[1] "$Ratio = 0.96$, 95\\% CI $[0.86,~1.07]$"

$estimate$t2_t4
[1] "$Ratio = 0.88$, 95\\% CI $[0.79,~0.98]$"

$estimate$t3_t4
[1] "$Ratio = 0.92$, 95\\% CI $[0.82,~1.02]$"


$statistic
$statistic$t1_t2
[1] "$t($\\infty$) = -0.77$, $p = .868$"

$statistic$t1_t3
[1] "$t($\\infty$) = -1.81$, $p = .270$"

$statistic$t1_t4
[1] "$t($\\infty$) = -3.93$, $p < .001$"

$statistic$t2_t3
[1] "$t($\\infty$) = -1.04$, $p = .727$"

$statistic$t2_t4
[1] "$t($\\infty$) = -3.17$, $p = .008$"

$statistic$t3_t4
[1] "$t($\\infty$) = -2.14$, $p = .140$"


$full_result
$full_result$t1_t2
[1] "$Ratio = 0.97$, 95\\% CI $[0.87,~1.08]$, $t($\\infty$) = -0.77$, $p = .868$"

$full_result$t1_t3
[1] "$Ratio = 0.93$, 95\\% CI $[0.83,~1.03]$, $t($\\infty$) = -1.81$, $p = .270$"

$full_result$t1_t4
[1] "$Ratio = 0.85$, 95\\% CI $[0.76,~0.94]$, $t($\\infty$) = -3.93$, $p < .001$"

$full_result$t2_t3
[1] "$Ratio = 0.96$, 95\\% CI $[0.86,~1.07]$, $t($\\infty$) = -1.04$, $p = .727$"

$full_result$t2_t4
[1] "$Ratio = 0.88$, 95\\% CI $[0.79,~0.98]$, $t($\\infty$) = -3.17$, $p = .008$"

$full_result$t3_t4
[1] "$Ratio = 0.92$, 95\\% CI $[0.82,~1.02]$, $t($\\infty$) = -2.14$, $p = .140$"


$table
A data.frame with 5 labelled columns:

      contrast estimate     conf.int statistic p.value
t1_t2  t1 / t2     0.97 [0.87, 1.08]     -0.77    .868
t1_t3  t1 / t3     0.93 [0.83, 1.03]     -1.81    .270
t1_t4  t1 / t4     0.85 [0.76, 0.94]     -3.93  < .001
t2_t3  t2 / t3     0.96 [0.86, 1.07]     -1.04    .727
t2_t4  t2 / t4     0.88 [0.79, 0.98]     -3.17    .008
t3_t4  t3 / t4     0.92 [0.82, 1.02]     -2.14    .140

contrast : Contrast 
estimate : $Ratio$ 
conf.int : 95\\% CI 
statistic: $t($\\infty$)$ 
p.value  : $p$ 
attr(,"class")
[1] "apa_results" "list"   
```

Where I am getting the error is, when I use the `type="response"` subset, although it is actually not necessary, because the data wasn't on the log scale, see example:

```
glmm <- mixed(errors~group*session*task+(1|participant), df)

contr<-emmeans(glmm, pairwise~session, type="response")

apa_print(contr$contrasts)

Error in if (x@misc$inv.lbl == "ratio" && !is.null(x@misc$predict.type) &&  : 
  missing value where TRUE/FALSE needed
```

Now, after I installed `remotes::install_github("crsh/papaja@emmeans")` after you asked and tried to see if the correct estimate label was working on the first example, I recieved a new error, see exmaple:

```
glmm <- mixed(errors~group*session*task+(1|participant), df, family='poisson', method='LRT')

contr<-emmeans(glmm, pairwise~session, type="response")

apa_print(contr$contrasts)

Error in printnum.default(tidy_x$estimate, ...) : 
  The parameter 'x' is NULL. Please provide a value for 'x'
```

Was I able to resolve the confusion about which branch did produce which error? :) Do you need additional information, like `session_info()`?

Mischa

**Comment by crsh** [comment] 2021-09-02 10:42
I'm using the `emmeans` branch and (after restarting R and executing your example in a clean R session) cannot reproduce the error:

~~~r
library("dplyr")
library("afex")
library("emmeans")
library("papaja")

participant<-c(1:40)
group<-c("intervention", "control","control","intervention","control")

df<-data.frame(participant,group) %>% 
  group_by(participant,group) %>% 
  summarise(session=c("t1","t2","t3","t4")) %>% 
  group_by(participant, group, session) %>% 
  summarise(task=c("a","b")) %>% 
  ungroup() %>% 
  mutate(errors=floor(runif(n=320,min=0,max=30)))

glmm <- mixed(errors~group*session*task+(1|participant), df, family='poisson', method='LRT')

contr<-emmeans(glmm, pairwise~session, type="response")

apa_print(contr$contrasts)
~~~

Could you follow the same steps and if you still get the error share your session info?

**Comment by Misch007** [comment] 2021-09-02 11:17
Hey @crsh,

I am sorry for the misinformation! I guess this was the point where the fact, that I am a total newbie and actually have no clue what I am doing came into play... I was facing some error messages during the installation, which I did not think were important, I still don't know why they appeared, but after I re-installed some other packages manually (xfun, tibble, stringi, htmltools), all my examples work perfectly now, thanks a lot and sorry for the inconvenience! 

Best regards,
Mischa

**Comment by crsh** [comment] 2021-09-02 12:19
Ah, yes, that makes sense. These errors keep happening every once in a while when installing from GitHub—I have no idea why. I hope that once we are on CRAN, this will be less of a problem.

Again, I really appreciate your comprehensive reports. So no need to worry. 😺

**Closed** 2022-03-17 15:06 UTC
Labels: bug
