### ISSUE TITLE
APA template generates duplicate references in reference list

### ISSUE THREAD

**Issue by dragfindel** [crsh/papaja#121] opened 2017-06-20 16:46 UTC
I wanted to make use of this template to simplify the process for my thesis, however, I have encountered some issues. Whenever I generate the document using Knitr, the references within the reference list are duplicated. 
For instance, a reference such as:
Borenstein, S. (2011). Why can’t US airlines make money? The American Economic Review,
101 (3), 233–237.
Will be included twice. 

When I look at the code, I notice that the following syntax is executed twice: 
`C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS Thesis.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output Thesis.tex --template` 
Followed by:
`C:\Users\XXX\Documents\R\win-library\3.3\papaja\rmarkdown\templates\apa6\resources\apa6.tex --highlight-style tango --latex-engine pdflatex --csl "C:\Users\XXXX\Documents\R\win-library\3.3\papaja\rmarkdown\templates\apa6\resources\apa6.csl" --filter pandoc-citeproc --filter _papaja_ampersand_filter.bat --bibliography Thesis.bib --filter pandoc-citeproc` 
 
To be clear; the preceding syntax is repeated twice. Given that I am using the standard template, I am assuming that the underlying code for the template causes the duplication. 

Any help?

**Comment by crsh** [comment] 2017-06-20 21:37
This is correct but should not be causing the problem you describe. If you have a reproducible example complete with R Markdown and BibTeX file I'd me more than happy to take a close look.

**Comment by dragfindel** [comment] 2017-06-20 22:07
That would be much appreciated! 
In the zip file I have included my .RMD file and the .BiB file that allows you to reproduce the problem. 
I am completely new to this, and thus I hope I do not cause any inconvenience. 
[Thesis.pdf](https://github.com/crsh/papaja/files/1089825/Thesis.pdf)
[Example.zip](https://github.com/crsh/papaja/files/1089819/Example.zip)

**Comment by crsh** [comment] 2017-07-03 16:48
Hi, sorry for the long delay. I finally found the time to take a look and I am unable to reproduce the problem. When I knit the document attached to your last post the result looks as expected: [Thesis.pdf](https://github.com/crsh/papaja/files/1120156/Thesis.pdf)

It has to be something to do with your set up. Could you supply your session info?

**Comment by crsh** [comment] 2017-11-29 01:52
I'll close this as I cannot reproduce this error. Please feel free to add details.

**Closed by crsh** 2017-11-29 01:52 UTC

**Comment by philipphoman** [comment] 2020-03-30 08:19
Reopening this. I'm also seeing duplicate references

**Comment by mariusbarth** [comment] 2020-03-30 08:25
Can you provide your session info so that we can track down the problem?

```
devtools::session_info()
```

**Comment by philipphoman** [comment] 2020-03-30 08:33
Thank you, sure:

─ Session info ───────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       Ubuntu 18.04.2 LTS          
 system   x86_64, linux-gnu           
 ui       X11                         
 language en_US                       
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Zurich               
 date     2020-03-30                  

─ Packages ───────────────────────────────────────────────────────────────────
 package      * version    date       lib source                      
 abind          1.4-5      2016-07-21 [1] CRAN (R 3.6.1)              
 arsenal      * 3.2.0      2019-06-13 [1] CRAN (R 3.6.1)              
 assertthat     0.2.1      2019-03-21 [1] CRAN (R 3.6.1)              
 backports    * 1.1.4      2019-04-10 [1] CRAN (R 3.6.1)              
 bookdown     * 0.12       2019-07-11 [1] CRAN (R 3.6.1)              
 boot           1.3-22     2019-04-26 [4] CRAN (R 3.6.0)              
 broom          0.5.2      2019-04-07 [1] CRAN (R 3.6.1)              
 callr          3.3.0      2019-07-04 [1] CRAN (R 3.6.1)              
 car          * 3.0-3      2019-05-27 [1] CRAN (R 3.6.1)              
 carData      * 3.0-2      2018-09-30 [1] CRAN (R 3.6.1)              
 cellranger     1.1.0      2016-07-27 [1] CRAN (R 3.6.1)              
 cli            1.1.0      2019-03-19 [1] CRAN (R 3.6.1)              
 colorspace     1.4-1      2019-03-18 [1] CRAN (R 3.6.1)              
 compareDF    * 2.0.2      2020-03-24 [1] CRAN (R 3.6.1)              
 CompQuadForm   1.4.3      2017-04-12 [1] CRAN (R 3.6.1)              
 cowplot      * 0.9.4      2019-01-08 [1] CRAN (R 3.6.1)              
 crayon         1.3.4      2017-09-16 [1] CRAN (R 3.6.1)              
 curl           3.3        2019-01-10 [1] CRAN (R 3.6.1)              
 data.table     1.12.2     2019-04-07 [1] CRAN (R 3.6.1)              
 desc           1.2.0      2018-05-01 [1] CRAN (R 3.6.1)              
 devtools     * 2.1.0      2019-07-06 [1] CRAN (R 3.6.1)              
 digest         0.6.20     2019-07-04 [1] CRAN (R 3.6.1)              
 dplyr        * 0.8.3      2019-07-04 [1] CRAN (R 3.6.1)              
 evaluate       0.14       2019-05-28 [1] CRAN (R 3.6.1)              
 fansi          0.4.0      2018-10-05 [1] CRAN (R 3.6.1)              
 forcats      * 0.4.0      2019-02-17 [1] CRAN (R 3.6.1)              
 foreign        0.8-70     2018-04-23 [4] CRAN (R 3.5.0)              
 fs             1.3.1      2019-05-06 [1] CRAN (R 3.6.1)              
 generics       0.0.2      2018-11-29 [1] CRAN (R 3.6.1)              
 ggplot2      * 3.2.0      2019-06-16 [1] CRAN (R 3.6.1)              
 ggpubr       * 0.2.4      2019-11-14 [1] CRAN (R 3.6.1)              
 ggsignif       0.6.0      2019-08-08 [1] CRAN (R 3.6.1)              
 glue           1.3.1      2019-03-12 [1] CRAN (R 3.6.1)              
 gtable         0.3.0      2019-03-25 [1] CRAN (R 3.6.1)              
 haven          2.2.0      2019-11-08 [1] CRAN (R 3.6.1)              
 here         * 0.1        2017-05-28 [1] CRAN (R 3.6.1)              
 highr          0.8        2019-03-20 [1] CRAN (R 3.6.1)              
 hms            0.4.2      2018-03-10 [1] CRAN (R 3.6.1)              
 htmltools      0.3.6      2017-04-28 [1] CRAN (R 3.6.1)              
 httr           1.4.0      2018-12-11 [1] CRAN (R 3.6.1)              
 jsonlite       1.6        2018-12-07 [1] CRAN (R 3.6.1)              
 knitr        * 1.26       2019-11-12 [1] CRAN (R 3.6.1)              
 labeling       0.3        2014-08-23 [1] CRAN (R 3.6.1)              
 lattice        0.20-38    2018-11-04 [4] CRAN (R 3.5.1)              
 lazyeval       0.2.2      2019-03-15 [1] CRAN (R 3.6.1)              
 lme4         * 1.1-21     2019-03-05 [1] CRAN (R 3.6.1)              
 lmerTest     * 3.1-0      2019-02-11 [1] CRAN (R 3.6.1)              
 lubridate      1.7.4      2018-04-11 [1] CRAN (R 3.6.1)              
 magrittr     * 1.5        2014-11-22 [1] CRAN (R 3.6.1)              
 MASS         * 7.3-51.1   2018-11-01 [4] CRAN (R 3.5.1)              
 Matrix       * 1.2-17     2019-03-22 [4] CRAN (R 3.5.3)              
 memoise        1.1.0      2017-04-21 [1] CRAN (R 3.6.1)              
 meta         * 4.11-0     2020-02-20 [1] CRAN (R 3.6.1)              
 metafor      * 2.1-0      2019-05-14 [1] CRAN (R 3.6.1)              
 minqa          1.2.4      2014-10-09 [1] CRAN (R 3.6.1)              
 modelr         0.1.4      2019-02-18 [1] CRAN (R 3.6.1)              
 munsell        0.5.0      2018-06-12 [1] CRAN (R 3.6.1)              
 nlme           3.1-140    2019-05-12 [4] CRAN (R 3.6.0)              
 nloptr         1.2.1      2018-10-03 [1] CRAN (R 3.6.1)              
 numDeriv       2016.8-1.1 2019-06-06 [1] CRAN (R 3.6.1)              
 openxlsx       4.1.0.1    2019-05-28 [1] CRAN (R 3.6.1)              
 pacman       * 0.5.1      2019-03-11 [1] CRAN (R 3.6.1)              
 papaja       * 0.1.0.9942 2020-03-30 [1] Github (crsh/papaja@9137f3f)
 pillar         1.4.2      2019-06-29 [1] CRAN (R 3.6.1)              
 pkgbuild       1.0.3      2019-03-20 [1] CRAN (R 3.6.1)              
 pkgconfig      2.0.2      2018-08-16 [1] CRAN (R 3.6.1)              
 pkgload        1.0.2      2018-10-29 [1] CRAN (R 3.6.1)              
 plyr           1.8.4      2016-06-08 [1] CRAN (R 3.6.1)              
 prettyunits    1.0.2      2015-07-13 [1] CRAN (R 3.6.1)              
 processx       3.4.0      2019-07-03 [1] CRAN (R 3.6.1)              
 ps             1.3.0      2018-12-21 [1] CRAN (R 3.6.1)              
 purrr        * 0.3.2      2019-03-15 [1] CRAN (R 3.6.1)              
 R6             2.4.0      2019-02-14 [1] CRAN (R 3.6.1)              
 Rcpp           1.0.1      2019-03-17 [1] CRAN (R 3.6.1)              
 readr        * 1.3.1      2018-12-21 [1] CRAN (R 3.6.1)              
 readxl       * 1.3.1      2019-03-13 [1] CRAN (R 3.6.1)              
 remotes        2.1.0      2019-06-24 [1] CRAN (R 3.6.1)              
 reshape2       1.4.3      2017-12-11 [1] CRAN (R 3.6.1)              
 rio            0.5.16     2018-11-26 [1] CRAN (R 3.6.1)              
 rJava        * 0.9-11     2019-03-29 [1] CRAN (R 3.6.1)              
 rlang          0.4.0      2019-06-25 [1] CRAN (R 3.6.1)              
 rmarkdown    * 1.13       2019-05-22 [1] CRAN (R 3.6.1)              
 rmdfiltr       0.1.2      2019-12-11 [1] CRAN (R 3.6.1)              
 robvis       * 0.3.0      2019-11-22 [1] CRAN (R 3.6.1)              
 rprojroot      1.3-2      2018-01-03 [1] CRAN (R 3.6.1)              
 rstudioapi     0.10       2019-03-19 [1] CRAN (R 3.6.1)              
 rvest          0.3.4      2019-05-15 [1] CRAN (R 3.6.1)              
 scales         1.0.0      2018-08-09 [1] CRAN (R 3.6.1)              
 sessioninfo    1.1.1      2018-11-05 [1] CRAN (R 3.6.1)              
 stringi        1.4.3      2019-03-12 [1] CRAN (R 3.6.1)              
 stringr      * 1.4.0      2019-02-10 [1] CRAN (R 3.6.1)              
 testthat       2.1.1      2019-04-23 [1] CRAN (R 3.6.1)              
 tibble       * 2.1.3      2019-06-06 [1] CRAN (R 3.6.1)              
 tidyr        * 0.8.3      2019-03-01 [1] CRAN (R 3.6.1)              
 tidyselect     0.2.5      2018-10-11 [1] CRAN (R 3.6.1)              
 tidyverse    * 1.2.1      2017-11-14 [1] CRAN (R 3.6.1)              
 tinytex        0.20       2020-02-25 [1] CRAN (R 3.6.1)              
 usethis      * 1.5.1      2019-07-04 [1] CRAN (R 3.6.1)              
 utf8           1.1.4      2018-05-24 [1] CRAN (R 3.6.1)              
 vctrs          0.2.0      2019-07-05 [1] CRAN (R 3.6.1)              
 withr          2.1.2      2018-03-15 [1] CRAN (R 3.6.1)              
 xfun           0.8        2019-06-25 [1] CRAN (R 3.6.1)              
 xml2           1.2.0      2018-01-24 [1] CRAN (R 3.6.1)              
 yaml           2.2.0      2018-07-25 [1] CRAN (R 3.6.1)              
 zeallot        0.1.0      2018-01-28 [1] CRAN (R 3.6.1)              
 zip            2.0.3      2019-07-03 [1] CRAN (R 3.6.1)              

[1] /home/homan/R
[2] /usr/local/lib/R/site-library
[3] /usr/lib/R/site-library
[4] /usr/lib/R/library

**Comment by mariusbarth** [comment] 2020-03-30 08:38
Can you update your library and then check if the problem persists? If you can't update all of your packages, could you try updating `rmarkdown`? It's only a guess, but there have been some major changes in this package that are related to his issue.

**Comment by philipphoman** [comment] 2020-03-30 08:43
Thanks, updating rmarkdown did the trick.

**Comment by mariusbarth** [comment] 2020-03-30 08:43
Great!
