### ISSUE TITLE
apa_table produces bad formatting in docx 

### ISSUE THREAD

**Issue by mdanka** [crsh/papaja#301] opened 2019-07-28 14:03 UTC
**Describe the bug**
`apa_table` with output `papaja::apa6_docx` produces badly formatted table on Mac and on Windows alike.

<img width="1392" alt="Screenshot 2019-07-28 at 15 59 19" src="https://user-images.githubusercontent.com/8069999/62007705-f5bfd280-b150-11e9-8a20-f707a122e168.png">

**To Reproduce**
In your `.Rmd` file given by the default papaja apa template, include the following section:

```
    # Table
    
    ```{r, code-chunk, echo = FALSE}
    my_table <- data.frame(col1 = c("a", "b", "c"), col2 = c(1, 2, 3))
    ```
    
    `r papaja::apa_table(my_table)`
```

In the header, set `output` to `papaja::apa6_docx`.

**Expected behavior**
The word doc contains an APA-style, well-formatted table, such as the one produced when `output` is set to `papaja::apa6_pdf`:

<img width="1318" alt="Screenshot 2019-07-28 at 15 59 46" src="https://user-images.githubusercontent.com/8069999/62007701-ec366a80-b150-11e9-81b9-4a8ecd060026.png">

**Screenshots**
Included above.

**Additional context**
The same happens both on Windows and Mac.

Using RStudio Version 1.1.463 on Mac.

Installed Papaja from the develop branch.

Note that `knitr::kable` does produce a table correctly:

```
    # Table

    ```{r, code-chunk, echo = FALSE}
    col1 <- c("a", "b", "c")
    col2 <- c(1, 2, 3)
    my_table <- data.frame(col1 = col1, col2 = col2)
    ```
    
    `r knitr::kable(my_table)`
    
    `r papaja::apa_table(my_table)`
```

<img width="1392" alt="Screenshot 2019-07-28 at 16 19 11" src="https://user-images.githubusercontent.com/8069999/62007917-9c0cd780-b153-11e9-813f-9f654f16d294.png">

**Comment by crsh** [comment] 2019-07-29 12:17
Thanks for the detailed report! I think this issue may already be fixed on the development branch. Could you retry after installing the latest version from there ( `devtools::install_github("crsh/papaja@devel")`)?

**Comment by mdanka** [comment] 2019-07-29 12:41
@crsh Thanks for the quick reply (and the great library!).

I was already using the develop branch, unfortunately.

I've just run the installation command you quoted, and received:

```
> devtools::install_github("crsh/papaja@devel")
Skipping install of 'papaja' from a github remote, the SHA1 (9c5cd2bd) has not changed since last install.
  Use `force = TRUE` to force installation
```

Just to be sure, I've now freshly started RStudio, rerun the installation with `force = TRUE`, loaded the library, and repeated the document generation - but unfortunately, the outcome was the same.

Can I do something else to help to debug or to reproduce the issue?

**Comment by crsh** [comment] 2019-07-29 12:52
Sorry, I can't test this myself right now because I'm on a Linux machine without Word. Does it work if you set `results = "asis"` in the chunk options?

**Comment by mdanka** [comment] 2019-07-29 14:40
That's OK, I'm happy to experiment along some ideas you have.

I executed the following code, but the result is visually the same:

```
    ```{r, code-chunk-table, echo = TRUE, results = 'asis'}
    papaja::apa_table(my_table)
    ```
```

Is the formatting expected to work, as in, has it been confirmed before, in which case it is something in my configuration/setup; or has it not yet been confirmed so far?

It's interesting that the table is rendered with `knitr::kable()`. What's the difference in execution? Does `papaja::apa_table()` defer the rendering to `kable` behind the scenes?

**Comment by HarryFisher1** [comment] 2019-08-16 07:03
I've been having an indenical issue on both Windows and Mac. No errors during complilation of the document, just the formatting of tables in word as shown by @mdanka.

I have the dev branch installed, and all chunks with tables have `r results = "asis" `.

Specs:
RStudio Version 1.2.1335
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)
papaja_0.1.0.9842 
knitr_1.24     
rmarkdown_1.14  

Thanks in advance!

**Comment by crsh** [comment] 2019-08-16 07:50
Sorry for the slow response. I was able to reproduce the problem and I think I have fixed it with my last commit. Could you reinstall, try again, and let me know whether it resolves the issue?

**Comment by HarryFisher1** [comment] 2019-08-16 08:51
Thanks! That does seem to have fixed most of the issues, however I had a few tables where I would pipe into apa_table(), and these still seem to have the same issue. For example:

    ```{r exampledata, results='asis'}

    exampledata <- tibble(Participant = c("1","1","2","3","3"),
         "X_1" = c("T1", "T2", "T1", "T1", "T2"),
         "X_2" = c("T2", "T3", "T2", "T2", "T3")) 

    apa_table(exampledata,
            align = "cccc",
            caption = "Example of the data arrangement used in the network.")
    ```

Produces the desired output in word, but

    ```{r exampledata, results='asis'}

     tibble(Participant = c("1","1","2","3","3"),
       "X_1" = c("T1", "T2", "T1", "T1", "T2"),
       "X_2" = c("T2", "T3", "T2", "T2", "T3")) %>% 
     apa_table(.,
            align = "cccc",
            caption = "Example of the data arrangement used in the network.")
    ```

does not work in word, but does work in pdf. Certainly not a major problem as you can just use the first example which might be a better way to use apa_table() anyway?

**Comment by crsh** [comment] 2019-08-16 09:02
Hmm, I cannot reproduce this problem. Both variants you post here work as expected for me. This is what I tried: [docx_tables.txt](https://github.com/crsh/papaja/files/3508842/docx_tables.txt)

**Comment by HarryFisher1** [comment] 2019-08-16 09:22
Ahh, some of the tables did not have the ".," as the first argument to apa_table(). For eample

    ```{r exampledata, results='asis'}

     tibble(Participant = c("1","1","2","3","3"),
                       "X_1" = c("T1", "T2", "T1", "T1", "T2"),
                       "X_2" = c("T2", "T3", "T2", "T2", "T3")) %>% 
      apa_table(align = "cccc",
                     caption = "Example of the data arrangement used in the network.")
    ```
Adding the ".," as the first argument has solved the problem for me.

Thanks!

**Comment by mdanka** [comment] 2019-08-16 20:31
@crsh It does work for me now :) Thank you very much for the quick fix.

Can you point me to the commit by any chance? I'd be curious to see what the fix was!

![Screenshot 2019-08-16 at 22 30 44](https://user-images.githubusercontent.com/8069999/63196426-92e99900-c075-11e9-8824-175ae019d54f.png)

**Comment by crsh** [comment] 2019-08-19 08:04
Sure, it's this one: https://github.com/crsh/papaja/commit/732e5b8921ae4b78a2bf7dbfd060c849d9a53b75

**Closed** 2020-01-16 23:49 UTC
Labels: bug
